// <auto-generated>
//     This code was generated by DevOp.Toon.SpecGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>


using System;
using System.Collections.Generic;
using System.Text.Json;
using DevOp.Toon;
using Xunit;


namespace DevOp.Toon.Tests.Decode;


[Trait("Category", "decode")]
public class ArraysTabular
{
    [Fact]
    [Trait("Description", "parses tabular arrays of uniform objects")]
    public void ParsesTabularArraysOfUniformObjects()
    {
        // Arrange
        var input =
"""
items[2]{sku,qty,price}:
  A1,2,9.99
  B2,1,14.5
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
{"items":[{"sku":"A1","qty":2,"price":9.99},{"sku":"B2","qty":1,"price":14.5}]}
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "parses nulls and quoted values in tabular rows")]
    public void ParsesNullsAndQuotedValuesInTabularRows()
    {
        // Arrange
        var input =
"""
items[2]{id,value}:
  1,null
  2,"test"
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
{"items":[{"id":1,"value":null},{"id":2,"value":"test"}]}
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "parses quoted colon in tabular row as data")]
    public void ParsesQuotedColonInTabularRowAsData()
    {
        // Arrange
        var input =
"""
items[2]{id,note}:
  1,"a:b"
  2,"c:d"
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
{"items":[{"id":1,"note":"a:b"},{"id":2,"note":"c:d"}]}
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "parses quoted header keys in tabular arrays")]
    public void ParsesQuotedHeaderKeysInTabularArrays()
    {
        // Arrange
        var input =
"""
items[2]{"order:id","full name"}:
  1,Ada
  2,Bob
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
{"items":[{"order:id":1,"full name":"Ada"},{"order:id":2,"full name":"Bob"}]}
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "parses quoted key with tabular array format")]
    public void ParsesQuotedKeyWithTabularArrayFormat()
    {
        // Arrange
        var input =
"""
"x-items"[2]{id,name}:
  1,Ada
  2,Bob
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
{"x-items":[{"id":1,"name":"Ada"},{"id":2,"name":"Bob"}]}
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "treats unquoted colon as terminator for tabular rows and start of key-value pair")]
    public void TreatsUnquotedColonAsTerminatorForTabularRowsAndStartOfKeyValuePair()
    {
        // Arrange
        var input =
"""
items[2]{id,name}:
  1,Alice
  2,Bob
count: 2
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
{"items":[{"id":1,"name":"Alice"},{"id":2,"name":"Bob"}],"count":2}
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

}
