// <auto-generated>
//     This code was generated by DevOp.Toon.SpecGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>


using System;
using System.Collections.Generic;
using System.Text.Json;
using DevOp.Toon;
using Xunit;


namespace DevOp.Toon.Tests.Decode;


[Trait("Category", "decode")]
public class ArraysPrimitive
{
    [Fact]
    [Trait("Description", "parses string arrays inline")]
    public void ParsesStringArraysInline()
    {
        // Arrange
        var input =
"""
tags[3]: reading,gaming,coding
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
{"tags":["reading","gaming","coding"]}
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "parses number arrays inline")]
    public void ParsesNumberArraysInline()
    {
        // Arrange
        var input =
"""
nums[3]: 1,2,3
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
{"nums":[1,2,3]}
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "parses mixed primitive arrays inline")]
    public void ParsesMixedPrimitiveArraysInline()
    {
        // Arrange
        var input =
"""
data[4]: x,y,true,10
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
{"data":["x","y",true,10]}
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "parses empty arrays")]
    public void ParsesEmptyArrays()
    {
        // Arrange
        var input =
"""
items[0]:
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
{"items":[]}
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "parses single-item array with empty string")]
    public void ParsesSingleItemArrayWithEmptyString()
    {
        // Arrange
        var input =
"""
items[1]: ""
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
{"items":[""]}
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "parses multi-item array with empty string")]
    public void ParsesMultiItemArrayWithEmptyString()
    {
        // Arrange
        var input =
"""
items[3]: a,"",b
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
{"items":["a","","b"]}
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "parses whitespace-only strings in arrays")]
    public void ParsesWhitespaceOnlyStringsInArrays()
    {
        // Arrange
        var input =
"""
items[2]: " ","  "
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
{"items":[" ","  "]}
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "parses strings with delimiters in arrays")]
    public void ParsesStringsWithDelimitersInArrays()
    {
        // Arrange
        var input =
"""
items[3]: a,"b,c","d:e"
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
{"items":["a","b,c","d:e"]}
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "parses strings that look like primitives when quoted")]
    public void ParsesStringsThatLookLikePrimitivesWhenQuoted()
    {
        // Arrange
        var input =
"""
items[4]: x,"true","42","-3.14"
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
{"items":["x","true","42","-3.14"]}
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "parses strings with structural tokens in arrays")]
    public void ParsesStringsWithStructuralTokensInArrays()
    {
        // Arrange
        var input =
"""
items[3]: "[5]","- item","{key}"
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
{"items":["[5]","- item","{key}"]}
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "parses quoted key with inline array")]
    public void ParsesQuotedKeyWithInlineArray()
    {
        // Arrange
        var input =
"""
"my-key"[3]: 1,2,3
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
{"my-key":[1,2,3]}
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "parses quoted key containing brackets with inline array")]
    public void ParsesQuotedKeyContainingBracketsWithInlineArray()
    {
        // Arrange
        var input =
"""
"key[test]"[3]: 1,2,3
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
{"key[test]":[1,2,3]}
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "parses quoted key with empty array")]
    public void ParsesQuotedKeyWithEmptyArray()
    {
        // Arrange
        var input =
"""
"x-custom"[0]:
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
{"x-custom":[]}
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

}
