// <auto-generated>
//     This code was generated by DevOp.Toon.SpecGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>


using System;
using System.Collections.Generic;
using System.Text.Json;
using DevOp.Toon;
using Xunit;


namespace DevOp.Toon.Tests.Decode;


[Trait("Category", "decode")]
public class ArraysNested
{
    [Fact]
    [Trait("Description", "parses list arrays for non-uniform objects")]
    public void ParsesListArraysForNonUniformObjects()
    {
        // Arrange
        var input =
"""
items[2]:
  - id: 1
    name: First
  - id: 2
    name: Second
    extra: true
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
{"items":[{"id":1,"name":"First"},{"id":2,"name":"Second","extra":true}]}
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "parses list arrays with empty items")]
    public void ParsesListArraysWithEmptyItems()
    {
        // Arrange
        var input =
"""
items[3]:
  - first
  - second
  -
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
{"items":["first","second",{}]}
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "parses list arrays with deeply nested objects")]
    public void ParsesListArraysWithDeeplyNestedObjects()
    {
        // Arrange
        var input =
"""
items[2]:
  - properties:
      state:
        type: string
  - id: 2
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
{"items":[{"properties":{"state":{"type":"string"}}},{"id":2}]}
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "parses list arrays containing objects with nested properties")]
    public void ParsesListArraysContainingObjectsWithNestedProperties()
    {
        // Arrange
        var input =
"""
items[1]:
  - id: 1
    nested:
      x: 1
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
{"items":[{"id":1,"nested":{"x":1}}]}
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "parses list items whose first field is a tabular array")]
    public void ParsesListItemsWhoseFirstFieldIsATabularArray()
    {
        // Arrange
        var input =
"""
items[1]:
  - users[2]{id,name}:
      1,Ada
      2,Bob
    status: active
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
{"items":[{"users":[{"id":1,"name":"Ada"},{"id":2,"name":"Bob"}],"status":"active"}]}
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "parses single-field list-item object with tabular array")]
    public void ParsesSingleFieldListItemObjectWithTabularArray()
    {
        // Arrange
        var input =
"""
items[1]:
  - users[2]{id,name}:
      1,Ada
      2,Bob
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
{"items":[{"users":[{"id":1,"name":"Ada"},{"id":2,"name":"Bob"}]}]}
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "parses objects containing arrays (including empty arrays) in list format")]
    public void ParsesObjectsContainingArraysIncludingEmptyArraysInListFormat()
    {
        // Arrange
        var input =
"""
items[1]:
  - name: Ada
    data[0]:
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
{"items":[{"name":"Ada","data":[]}]}
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "parses arrays of arrays within objects")]
    public void ParsesArraysOfArraysWithinObjects()
    {
        // Arrange
        var input =
"""
items[1]:
  - matrix[2]:
      - [2]: 1,2
      - [2]: 3,4
    name: grid
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
{"items":[{"matrix":[[1,2],[3,4]],"name":"grid"}]}
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "parses nested arrays of primitives")]
    public void ParsesNestedArraysOfPrimitives()
    {
        // Arrange
        var input =
"""
pairs[2]:
  - [2]: a,b
  - [2]: c,d
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
{"pairs":[["a","b"],["c","d"]]}
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "parses quoted strings and mixed lengths in nested arrays")]
    public void ParsesQuotedStringsAndMixedLengthsInNestedArrays()
    {
        // Arrange
        var input =
"""
pairs[2]:
  - [2]: a,b
  - [3]: "c,d","e:f","true"
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
{"pairs":[["a","b"],["c,d","e:f","true"]]}
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "parses empty inner arrays")]
    public void ParsesEmptyInnerArrays()
    {
        // Arrange
        var input =
"""
pairs[2]:
  - [0]:
  - [0]:
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
{"pairs":[[],[]]}
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "parses mixed-length inner arrays")]
    public void ParsesMixedLengthInnerArrays()
    {
        // Arrange
        var input =
"""
pairs[2]:
  - [1]: 1
  - [2]: 2,3
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
{"pairs":[[1],[2,3]]}
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "parses root-level primitive array inline")]
    public void ParsesRootLevelPrimitiveArrayInline()
    {
        // Arrange
        var input =
"""
[5]: x,y,"true",true,10
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
["x","y","true",true,10]
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "parses root-level array of uniform objects in tabular format")]
    public void ParsesRootLevelArrayOfUniformObjectsInTabularFormat()
    {
        // Arrange
        var input =
"""
[2]{id}:
  1
  2
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
[{"id":1},{"id":2}]
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "parses root-level array of non-uniform objects in list format")]
    public void ParsesRootLevelArrayOfNonUniformObjectsInListFormat()
    {
        // Arrange
        var input =
"""
[2]:
  - id: 1
  - id: 2
    name: Ada
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
[{"id":1},{"id":2,"name":"Ada"}]
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "parses root-level array mixing primitive, object, and array of objects in list format")]
    public void ParsesRootLevelArrayMixingPrimitiveObjectAndArrayOfObjectsInListFormat()
    {
        // Arrange
        var input =
"""
[3]:
  - summary
  - id: 1
    name: Ada
  - [2]:
    - id: 2
    - status: draft
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
["summary",{"id":1,"name":"Ada"},[{"id":2},{"status":"draft"}]]
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "parses root-level array of arrays")]
    public void ParsesRootLevelArrayOfArrays()
    {
        // Arrange
        var input =
"""
[2]:
  - [2]: 1,2
  - [0]:
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
[[1,2],[]]
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "parses empty root-level array")]
    public void ParsesEmptyRootLevelArray()
    {
        // Arrange
        var input =
"""
[0]:
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
[]
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "parses complex mixed object with arrays and nested objects")]
    public void ParsesComplexMixedObjectWithArraysAndNestedObjects()
    {
        // Arrange
        var input =
"""
user:
  id: 123
  name: Ada
  tags[2]: reading,gaming
  active: true
  prefs[0]:
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
{"user":{"id":123,"name":"Ada","tags":["reading","gaming"],"active":true,"prefs":[]}}
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "parses arrays mixing primitives, objects, and strings in list format")]
    public void ParsesArraysMixingPrimitivesObjectsAndStringsInListFormat()
    {
        // Arrange
        var input =
"""
items[3]:
  - 1
  - a: 1
  - text
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
{"items":[1,{"a":1},"text"]}
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "parses arrays mixing objects and arrays")]
    public void ParsesArraysMixingObjectsAndArrays()
    {
        // Arrange
        var input =
"""
items[2]:
  - a: 1
  - [2]: 1,2
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
{"items":[{"a":1},[1,2]]}
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "parses quoted key with list array format")]
    public void ParsesQuotedKeyWithListArrayFormat()
    {
        // Arrange
        var input =
"""
"x-items"[2]:
  - id: 1
  - id: 2
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
{"x-items":[{"id":1},{"id":2}]}
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

}
