// <auto-generated>
//     This code was generated by DevOp.Toon.SpecGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>


using System;
using System.Collections.Generic;
using System.Text.Json;
using DevOp.Toon;
using Xunit;


namespace DevOp.Toon.Tests.Decode;


[Trait("Category", "decode")]
public class BlankLines
{
    [Fact]
    [Trait("Description", "throws on blank line inside list array")]
    public void ThrowsOnBlankLineInsideListArray()
    {
        // Arrange
        var input =
"""
items[3]:
  - a

  - b
  - c
""";

        // Act & Assert
        var options = new ToonDecodeOptions
        {
            Indent = 2,
            Strict = true,
        };

        Assert.Throws<ToonFormatException>(() => ToonDecoder.Decode(input, options));
    }

    [Fact]
    [Trait("Description", "throws on blank line inside tabular array")]
    public void ThrowsOnBlankLineInsideTabularArray()
    {
        // Arrange
        var input =
"""
items[2]{id}:
  1

  2
""";

        // Act & Assert
        var options = new ToonDecodeOptions
        {
            Indent = 2,
            Strict = true,
        };

        Assert.Throws<ToonFormatException>(() => ToonDecoder.Decode(input, options));
    }

    [Fact]
    [Trait("Description", "throws on multiple blank lines inside array")]
    public void ThrowsOnMultipleBlankLinesInsideArray()
    {
        // Arrange
        var input =
"""
items[2]:
  - a


  - b
""";

        // Act & Assert
        var options = new ToonDecodeOptions
        {
            Indent = 2,
            Strict = true,
        };

        Assert.Throws<ToonFormatException>(() => ToonDecoder.Decode(input, options));
    }

    [Fact]
    [Trait("Description", "throws on blank line with spaces inside array")]
    public void ThrowsOnBlankLineWithSpacesInsideArray()
    {
        // Arrange
        var input =
"""
items[2]:
  - a
  
  - b
""";

        // Act & Assert
        var options = new ToonDecodeOptions
        {
            Indent = 2,
            Strict = true,
        };

        Assert.Throws<ToonFormatException>(() => ToonDecoder.Decode(input, options));
    }

    [Fact]
    [Trait("Description", "throws on blank line in nested list array")]
    public void ThrowsOnBlankLineInNestedListArray()
    {
        // Arrange
        var input =
"""
outer[2]:
  - inner[2]:
    - a

    - b
  - x
""";

        // Act & Assert
        var options = new ToonDecodeOptions
        {
            Indent = 2,
            Strict = true,
        };

        Assert.Throws<ToonFormatException>(() => ToonDecoder.Decode(input, options));
    }

    [Fact]
    [Trait("Description", "accepts blank line between root-level fields")]
    public void AcceptsBlankLineBetweenRootLevelFields()
    {
        // Arrange
        var input =
"""
a: 1

b: 2
""";

        // Act & Assert
        var options = new ToonDecodeOptions
        {
            Indent = 2,
            Strict = true,
        };

        var result = ToonDecoder.Decode(input, options);

        var expected = ToonNode.Parse("""
{"a":1,"b":2}
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "accepts trailing newline at end of file")]
    public void AcceptsTrailingNewlineAtEndOfFile()
    {
        // Arrange
        var input =
"""
a: 1

""";

        // Act & Assert
        var options = new ToonDecodeOptions
        {
            Indent = 2,
            Strict = true,
        };

        var result = ToonDecoder.Decode(input, options);

        var expected = ToonNode.Parse("""
{"a":1}
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "accepts multiple trailing newlines")]
    public void AcceptsMultipleTrailingNewlines()
    {
        // Arrange
        var input =
"""
a: 1



""";

        // Act & Assert
        var options = new ToonDecodeOptions
        {
            Indent = 2,
            Strict = true,
        };

        var result = ToonDecoder.Decode(input, options);

        var expected = ToonNode.Parse("""
{"a":1}
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "accepts blank line after array ends")]
    public void AcceptsBlankLineAfterArrayEnds()
    {
        // Arrange
        var input =
"""
items[1]:
  - a

b: 2
""";

        // Act & Assert
        var options = new ToonDecodeOptions
        {
            Indent = 2,
            Strict = true,
        };

        var result = ToonDecoder.Decode(input, options);

        var expected = ToonNode.Parse("""
{"items":["a"],"b":2}
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "accepts blank line between nested object fields")]
    public void AcceptsBlankLineBetweenNestedObjectFields()
    {
        // Arrange
        var input =
"""
a:
  b: 1

  c: 2
""";

        // Act & Assert
        var options = new ToonDecodeOptions
        {
            Indent = 2,
            Strict = true,
        };

        var result = ToonDecoder.Decode(input, options);

        var expected = ToonNode.Parse("""
{"a":{"b":1,"c":2}}
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "ignores blank lines inside list array when strict=false")]
    public void IgnoresBlankLinesInsideListArrayWhenStrictFalse()
    {
        // Arrange
        var input =
"""
items[3]:
  - a

  - b
  - c
""";

        // Act & Assert
        var options = new ToonDecodeOptions
        {
            Indent = 2,
            Strict = false,
        };

        var result = ToonDecoder.Decode(input, options);

        var expected = ToonNode.Parse("""
{"items":["a","b","c"]}
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "ignores blank lines inside tabular array when strict=false")]
    public void IgnoresBlankLinesInsideTabularArrayWhenStrictFalse()
    {
        // Arrange
        var input =
"""
items[2]{id,name}:
  1,Alice

  2,Bob
""";

        // Act & Assert
        var options = new ToonDecodeOptions
        {
            Indent = 2,
            Strict = false,
        };

        var result = ToonDecoder.Decode(input, options);

        var expected = ToonNode.Parse("""
{"items":[{"id":1,"name":"Alice"},{"id":2,"name":"Bob"}]}
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "ignores multiple blank lines in arrays when strict=false")]
    public void IgnoresMultipleBlankLinesInArraysWhenStrictFalse()
    {
        // Arrange
        var input =
"""
items[2]:
  - a


  - b
""";

        // Act & Assert
        var options = new ToonDecodeOptions
        {
            Indent = 2,
            Strict = false,
        };

        var result = ToonDecoder.Decode(input, options);

        var expected = ToonNode.Parse("""
{"items":["a","b"]}
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

}
