// <auto-generated>
//     This code was generated by DevOp.Toon.SpecGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>


using System;
using System.Collections.Generic;
using System.Text.Json;
using DevOp.Toon;
using Xunit;


namespace DevOp.Toon.Tests.Decode;


[Trait("Category", "decode")]
public class Delimiters
{
    [Fact]
    [Trait("Description", "parses primitive arrays with tab delimiter")]
    public void ParsesPrimitiveArraysWithTabDelimiter()
    {
        // Arrange
        var input =
"""
tags[3	]: reading	gaming	coding
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
{"tags":["reading","gaming","coding"]}
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "parses primitive arrays with pipe delimiter")]
    public void ParsesPrimitiveArraysWithPipeDelimiter()
    {
        // Arrange
        var input =
"""
tags[3|]: reading|gaming|coding
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
{"tags":["reading","gaming","coding"]}
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "parses primitive arrays with comma delimiter")]
    public void ParsesPrimitiveArraysWithCommaDelimiter()
    {
        // Arrange
        var input =
"""
tags[3]: reading,gaming,coding
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
{"tags":["reading","gaming","coding"]}
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "parses tabular arrays with tab delimiter")]
    public void ParsesTabularArraysWithTabDelimiter()
    {
        // Arrange
        var input =
"""
items[2	]{sku	qty	price}:
  A1	2	9.99
  B2	1	14.5
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
{"items":[{"sku":"A1","qty":2,"price":9.99},{"sku":"B2","qty":1,"price":14.5}]}
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "parses tabular arrays with pipe delimiter")]
    public void ParsesTabularArraysWithPipeDelimiter()
    {
        // Arrange
        var input =
"""
items[2|]{sku|qty|price}:
  A1|2|9.99
  B2|1|14.5
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
{"items":[{"sku":"A1","qty":2,"price":9.99},{"sku":"B2","qty":1,"price":14.5}]}
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "parses nested arrays with tab delimiter")]
    public void ParsesNestedArraysWithTabDelimiter()
    {
        // Arrange
        var input =
"""
pairs[2	]:
  - [2	]: a	b
  - [2	]: c	d
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
{"pairs":[["a","b"],["c","d"]]}
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "parses nested arrays with pipe delimiter")]
    public void ParsesNestedArraysWithPipeDelimiter()
    {
        // Arrange
        var input =
"""
pairs[2|]:
  - [2|]: a|b
  - [2|]: c|d
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
{"pairs":[["a","b"],["c","d"]]}
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "parses nested arrays inside list items with default comma delimiter")]
    public void ParsesNestedArraysInsideListItemsWithDefaultCommaDelimiter()
    {
        // Arrange
        var input =
"""
items[1	]:
  - tags[3]: a,b,c
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
{"items":[{"tags":["a","b","c"]}]}
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "parses nested arrays inside list items with default comma delimiter when parent uses pipe")]
    public void ParsesNestedArraysInsideListItemsWithDefaultCommaDelimiterWhenParentUsesPipe()
    {
        // Arrange
        var input =
"""
items[1|]:
  - tags[3]: a,b,c
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
{"items":[{"tags":["a","b","c"]}]}
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "parses root-level array with tab delimiter")]
    public void ParsesRootLevelArrayWithTabDelimiter()
    {
        // Arrange
        var input =
"""
[3	]: x	y	z
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
["x","y","z"]
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "parses root-level array with pipe delimiter")]
    public void ParsesRootLevelArrayWithPipeDelimiter()
    {
        // Arrange
        var input =
"""
[3|]: x|y|z
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
["x","y","z"]
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "parses root-level array of objects with tab delimiter")]
    public void ParsesRootLevelArrayOfObjectsWithTabDelimiter()
    {
        // Arrange
        var input =
"""
[2	]{id}:
  1
  2
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
[{"id":1},{"id":2}]
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "parses root-level array of objects with pipe delimiter")]
    public void ParsesRootLevelArrayOfObjectsWithPipeDelimiter()
    {
        // Arrange
        var input =
"""
[2|]{id}:
  1
  2
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
[{"id":1},{"id":2}]
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "parses values containing tab delimiter when quoted")]
    public void ParsesValuesContainingTabDelimiterWhenQuoted()
    {
        // Arrange
        var input =
"""
items[3	]: a	"b\tc"	d
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
{"items":["a","b\tc","d"]}
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "parses values containing pipe delimiter when quoted")]
    public void ParsesValuesContainingPipeDelimiterWhenQuoted()
    {
        // Arrange
        var input =
"""
items[3|]: a|"b|c"|d
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
{"items":["a","b|c","d"]}
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "does not split on commas when using tab delimiter")]
    public void DoesNotSplitOnCommasWhenUsingTabDelimiter()
    {
        // Arrange
        var input =
"""
items[2	]: a,b	c,d
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
{"items":["a,b","c,d"]}
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "does not split on commas when using pipe delimiter")]
    public void DoesNotSplitOnCommasWhenUsingPipeDelimiter()
    {
        // Arrange
        var input =
"""
items[2|]: a,b|c,d
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
{"items":["a,b","c,d"]}
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "parses tabular values containing comma with comma delimiter")]
    public void ParsesTabularValuesContainingCommaWithCommaDelimiter()
    {
        // Arrange
        var input =
"""
items[2]{id,note}:
  1,"a,b"
  2,"c,d"
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
{"items":[{"id":1,"note":"a,b"},{"id":2,"note":"c,d"}]}
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "does not require quoting commas with tab delimiter")]
    public void DoesNotRequireQuotingCommasWithTabDelimiter()
    {
        // Arrange
        var input =
"""
items[2	]{id	note}:
  1	a,b
  2	c,d
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
{"items":[{"id":1,"note":"a,b"},{"id":2,"note":"c,d"}]}
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "does not require quoting commas in object values")]
    public void DoesNotRequireQuotingCommasInObjectValues()
    {
        // Arrange
        var input =
"""
note: a,b
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
{"note":"a,b"}
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "object values in list items follow document delimiter")]
    public void ObjectValuesInListItemsFollowDocumentDelimiter()
    {
        // Arrange
        var input =
"""
items[2	]:
  - status: a,b
  - status: c,d
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
{"items":[{"status":"a,b"},{"status":"c,d"}]}
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "object values with comma must be quoted when document delimiter is comma")]
    public void ObjectValuesWithCommaMustBeQuotedWhenDocumentDelimiterIsComma()
    {
        // Arrange
        var input =
"""
items[2]:
  - status: "a,b"
  - status: "c,d"
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
{"items":[{"status":"a,b"},{"status":"c,d"}]}
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "parses nested array values containing pipe delimiter")]
    public void ParsesNestedArrayValuesContainingPipeDelimiter()
    {
        // Arrange
        var input =
"""
pairs[1|]:
  - [2|]: a|"b|c"
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
{"pairs":[["a","b|c"]]}
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "parses nested array values containing tab delimiter")]
    public void ParsesNestedArrayValuesContainingTabDelimiter()
    {
        // Arrange
        var input =
"""
pairs[1	]:
  - [2	]: a	"b\tc"
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
{"pairs":[["a","b\tc"]]}
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "preserves quoted ambiguity with pipe delimiter")]
    public void PreservesQuotedAmbiguityWithPipeDelimiter()
    {
        // Arrange
        var input =
"""
items[3|]: "true"|"42"|"-3.14"
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
{"items":["true","42","-3.14"]}
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "preserves quoted ambiguity with tab delimiter")]
    public void PreservesQuotedAmbiguityWithTabDelimiter()
    {
        // Arrange
        var input =
"""
items[3	]: "true"	"42"	"-3.14"
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
{"items":["true","42","-3.14"]}
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "parses structural-looking strings when quoted with pipe delimiter")]
    public void ParsesStructuralLookingStringsWhenQuotedWithPipeDelimiter()
    {
        // Arrange
        var input =
"""
items[3|]: "[5]"|"{key}"|"- item"
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
{"items":["[5]","{key}","- item"]}
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "parses structural-looking strings when quoted with tab delimiter")]
    public void ParsesStructuralLookingStringsWhenQuotedWithTabDelimiter()
    {
        // Arrange
        var input =
"""
items[3	]: "[5]"	"{key}"	"- item"
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
{"items":["[5]","{key}","- item"]}
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "parses tabular headers with keys containing the active delimiter")]
    public void ParsesTabularHeadersWithKeysContainingTheActiveDelimiter()
    {
        // Arrange
        var input =
"""
items[2|]{"a|b"}:
  1
  2
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
{"items":[{"a|b":1},{"a|b":2}]}
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

}
