// <auto-generated>
//     This code was generated by DevOp.Toon.SpecGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>


using System;
using System.Collections.Generic;
using System.Text.Json;
using DevOp.Toon;
using Xunit;


namespace DevOp.Toon.Tests.Decode;


[Trait("Category", "decode")]
public class IndentationErrors
{
    [Fact]
    [Trait("Description", "throws on object field with non-multiple indentation (3 spaces with indent=2)")]
    public void ThrowsOnObjectFieldWithNonMultipleIndentation3SpacesWithIndent2()
    {
        // Arrange
        var input =
"""
a:
   b: 1
""";

        // Act & Assert
        var options = new ToonDecodeOptions
        {
            Indent = 2,
            Strict = true,
        };

        Assert.Throws<ToonFormatException>(() => ToonDecoder.Decode(input, options));
    }

    [Fact]
    [Trait("Description", "throws on list item with non-multiple indentation (3 spaces with indent=2)")]
    public void ThrowsOnListItemWithNonMultipleIndentation3SpacesWithIndent2()
    {
        // Arrange
        var input =
"""
items[2]:
   - id: 1
   - id: 2
""";

        // Act & Assert
        var options = new ToonDecodeOptions
        {
            Indent = 2,
            Strict = true,
        };

        Assert.Throws<ToonFormatException>(() => ToonDecoder.Decode(input, options));
    }

    [Fact]
    [Trait("Description", "throws on non-multiple indentation with custom indent=4 (3 spaces)")]
    public void ThrowsOnNonMultipleIndentationWithCustomIndent43Spaces()
    {
        // Arrange
        var input =
"""
a:
   b: 1
""";

        // Act & Assert
        var options = new ToonDecodeOptions
        {
            Indent = 4,
            Strict = true,
        };

        Assert.Throws<ToonFormatException>(() => ToonDecoder.Decode(input, options));
    }

    [Fact]
    [Trait("Description", "accepts correct indentation with custom indent size (4 spaces with indent=4)")]
    public void AcceptsCorrectIndentationWithCustomIndentSize4SpacesWithIndent4()
    {
        // Arrange
        var input =
"""
a:
    b: 1
""";

        // Act & Assert
        var options = new ToonDecodeOptions
        {
            Indent = 4,
            Strict = true,
        };

        var result = ToonDecoder.Decode(input, options);

        var expected = ToonNode.Parse("""
{"a":{"b":1}}
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "throws on tab character used in indentation")]
    public void ThrowsOnTabCharacterUsedInIndentation()
    {
        // Arrange
        var input =
"""
a:
	b: 1
""";

        // Act & Assert
        var options = new ToonDecodeOptions
        {
            Indent = 2,
            Strict = true,
        };

        Assert.Throws<ToonFormatException>(() => ToonDecoder.Decode(input, options));
    }

    [Fact]
    [Trait("Description", "throws on mixed tabs and spaces in indentation")]
    public void ThrowsOnMixedTabsAndSpacesInIndentation()
    {
        // Arrange
        var input =
"""
a:
 	b: 1
""";

        // Act & Assert
        var options = new ToonDecodeOptions
        {
            Indent = 2,
            Strict = true,
        };

        Assert.Throws<ToonFormatException>(() => ToonDecoder.Decode(input, options));
    }

    [Fact]
    [Trait("Description", "throws on tab at start of line")]
    public void ThrowsOnTabAtStartOfLine()
    {
        // Arrange
        var input =
"""
	a: 1
""";

        // Act & Assert
        var options = new ToonDecodeOptions
        {
            Indent = 2,
            Strict = true,
        };

        Assert.Throws<ToonFormatException>(() => ToonDecoder.Decode(input, options));
    }

    [Fact]
    [Trait("Description", "accepts tabs in quoted string values")]
    public void AcceptsTabsInQuotedStringValues()
    {
        // Arrange
        var input =
"""
text: "hello	world"
""";

        // Act & Assert
        var options = new ToonDecodeOptions
        {
            Indent = 2,
            Strict = true,
        };

        var result = ToonDecoder.Decode(input, options);

        var expected = ToonNode.Parse("""
{"text":"hello\tworld"}
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "accepts tabs in quoted keys")]
    public void AcceptsTabsInQuotedKeys()
    {
        // Arrange
        var input =
"""
"key	tab": value
""";

        // Act & Assert
        var options = new ToonDecodeOptions
        {
            Indent = 2,
            Strict = true,
        };

        var result = ToonDecoder.Decode(input, options);

        var expected = ToonNode.Parse("""
{"key\ttab":"value"}
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "accepts tabs in quoted array elements")]
    public void AcceptsTabsInQuotedArrayElements()
    {
        // Arrange
        var input =
"""
items[2]: "a	b","c	d"
""";

        // Act & Assert
        var options = new ToonDecodeOptions
        {
            Indent = 2,
            Strict = true,
        };

        var result = ToonDecoder.Decode(input, options);

        var expected = ToonNode.Parse("""
{"items":["a\tb","c\td"]}
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "accepts non-multiple indentation when strict=false")]
    public void AcceptsNonMultipleIndentationWhenStrictFalse()
    {
        // Arrange
        var input =
"""
a:
   b: 1
""";

        // Act & Assert
        var options = new ToonDecodeOptions
        {
            Indent = 2,
            Strict = false,
        };

        var result = ToonDecoder.Decode(input, options);

        var expected = ToonNode.Parse("""
{"a":{"b":1}}
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "accepts deeply nested non-multiples when strict=false")]
    public void AcceptsDeeplyNestedNonMultiplesWhenStrictFalse()
    {
        // Arrange
        var input =
"""
a:
   b:
     c: 1
""";

        // Act & Assert
        var options = new ToonDecodeOptions
        {
            Indent = 2,
            Strict = false,
        };

        var result = ToonDecoder.Decode(input, options);

        var expected = ToonNode.Parse("""
{"a":{"b":{"c":1}}}
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "parses empty lines without validation errors")]
    public void ParsesEmptyLinesWithoutValidationErrors()
    {
        // Arrange
        var input =
"""
a: 1

b: 2
""";

        // Act & Assert
        var options = new ToonDecodeOptions
        {
            Indent = 2,
            Strict = true,
        };

        var result = ToonDecoder.Decode(input, options);

        var expected = ToonNode.Parse("""
{"a":1,"b":2}
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "parses root-level content (0 indentation) as always valid")]
    public void ParsesRootLevelContent0IndentationAsAlwaysValid()
    {
        // Arrange
        var input =
"""
a: 1
b: 2
c: 3
""";

        // Act & Assert
        var options = new ToonDecodeOptions
        {
            Indent = 2,
            Strict = true,
        };

        var result = ToonDecoder.Decode(input, options);

        var expected = ToonNode.Parse("""
{"a":1,"b":2,"c":3}
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "parses lines with only spaces without validation if empty")]
    public void ParsesLinesWithOnlySpacesWithoutValidationIfEmpty()
    {
        // Arrange
        var input =
"""
a: 1
   
b: 2
""";

        // Act & Assert
        var options = new ToonDecodeOptions
        {
            Indent = 2,
            Strict = true,
        };

        var result = ToonDecoder.Decode(input, options);

        var expected = ToonNode.Parse("""
{"a":1,"b":2}
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

}
