// <auto-generated>
//     This code was generated by DevOp.Toon.SpecGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>


using System;
using System.Collections.Generic;
using System.Text.Json;
using DevOp.Toon;
using Xunit;


namespace DevOp.Toon.Tests.Decode;


[Trait("Category", "decode")]
public class Numbers
{
    [Fact]
    [Trait("Description", "parses number with trailing zeros in fractional part")]
    public void ParsesNumberWithTrailingZerosInFractionalPart()
    {
        // Arrange
        var input =
"""
value: 1.5000
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
{"value":1.5}
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "parses negative number with positive exponent")]
    public void ParsesNegativeNumberWithPositiveExponent()
    {
        // Arrange
        var input =
"""
value: -1E+03
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
{"value":-1000}
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "parses lowercase exponent")]
    public void ParsesLowercaseExponent()
    {
        // Arrange
        var input =
"""
value: 2.5e2
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
{"value":250}
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "parses uppercase exponent with negative sign")]
    public void ParsesUppercaseExponentWithNegativeSign()
    {
        // Arrange
        var input =
"""
value: 3E-02
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
{"value":0.03}
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "parses negative zero as zero")]
    public void ParsesNegativeZeroAsZero()
    {
        // Arrange
        var input =
"""
value: -0
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
{"value":0}
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "parses negative zero with fractional part")]
    public void ParsesNegativeZeroWithFractionalPart()
    {
        // Arrange
        var input =
"""
value: -0.0
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
{"value":0}
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "parses array with mixed numeric forms")]
    public void ParsesArrayWithMixedNumericForms()
    {
        // Arrange
        var input =
"""
nums[5]: 42,-1E+03,1.5000,-0,2.5e2
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
{"nums":[42,-1000,1.5,0,250]}
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "treats leading zero as string not number")]
    public void TreatsLeadingZeroAsStringNotNumber()
    {
        // Arrange
        var input =
"""
value: 05
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
{"value":"05"}
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "parses very small exponent")]
    public void ParsesVerySmallExponent()
    {
        // Arrange
        var input =
"""
value: 1e-10
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
{"value":0.0000000001}
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "parses integer with positive exponent")]
    public void ParsesIntegerWithPositiveExponent()
    {
        // Arrange
        var input =
"""
value: 5E+00
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
{"value":5}
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "parses exponent notation")]
    public void ParsesExponentNotation()
    {
        // Arrange
        var input =
"""
1e6
""";

        // Act & Assert
        var result = ToonDecoder.Decode<double>(input);

        var expected = 1000000;

        Assert.Equal(result, expected);
    }

    [Fact]
    [Trait("Description", "parses exponent notation with uppercase E")]
    public void ParsesExponentNotationWithUppercaseE()
    {
        // Arrange
        var input =
"""
1E+6
""";

        // Act & Assert
        var result = ToonDecoder.Decode<double>(input);

        var expected = 1000000;

        Assert.Equal(result, expected);
    }

    [Fact]
    [Trait("Description", "parses negative exponent notation")]
    public void ParsesNegativeExponentNotation()
    {
        // Arrange
        var input =
"""
-1e-3
""";

        // Act & Assert
        var result = ToonDecoder.Decode<double>(input);

        var expected = -0.001;

        Assert.Equal(result, expected);
    }

    [Fact]
    [Trait("Description", "treats unquoted leading-zero number as string")]
    public void TreatsUnquotedLeadingZeroNumberAsString()
    {
        // Arrange
        var input =
"""
05
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
"05"
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "treats unquoted multi-leading-zero as string")]
    public void TreatsUnquotedMultiLeadingZeroAsString()
    {
        // Arrange
        var input =
"""
007
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
"007"
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "treats unquoted octal-like as string")]
    public void TreatsUnquotedOctalLikeAsString()
    {
        // Arrange
        var input =
"""
0123
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
"0123"
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "treats leading-zero in object value as string")]
    public void TreatsLeadingZeroInObjectValueAsString()
    {
        // Arrange
        var input =
"""
a: 05
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
{"a":"05"}
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "treats leading-zeros in array as strings")]
    public void TreatsLeadingZerosInArrayAsStrings()
    {
        // Arrange
        var input =
"""
nums[3]: 05,007,0123
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
{"nums":["05","007","0123"]}
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

}
