// <auto-generated>
//     This code was generated by DevOp.Toon.SpecGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>


using System;
using System.Collections.Generic;
using System.Text.Json;
using DevOp.Toon;
using Xunit;


namespace DevOp.Toon.Tests.Decode;


[Trait("Category", "decode")]
public class Objects
{
    [Fact]
    [Trait("Description", "parses objects with primitive values")]
    public void ParsesObjectsWithPrimitiveValues()
    {
        // Arrange
        var input =
"""
id: 123
name: Ada
active: true
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
{"id":123,"name":"Ada","active":true}
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "parses null values in objects")]
    public void ParsesNullValuesInObjects()
    {
        // Arrange
        var input =
"""
id: 123
value: null
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
{"id":123,"value":null}
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "parses empty nested object header")]
    public void ParsesEmptyNestedObjectHeader()
    {
        // Arrange
        var input =
"""
user:
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
{"user":{}}
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "parses quoted object value with colon")]
    public void ParsesQuotedObjectValueWithColon()
    {
        // Arrange
        var input =
"""
note: "a:b"
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
{"note":"a:b"}
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "parses quoted object value with comma")]
    public void ParsesQuotedObjectValueWithComma()
    {
        // Arrange
        var input =
"""
note: "a,b"
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
{"note":"a,b"}
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "parses quoted object value with newline escape")]
    public void ParsesQuotedObjectValueWithNewlineEscape()
    {
        // Arrange
        var input =
"""
text: "line1\nline2"
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
{"text":"line1\nline2"}
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "parses quoted object value with escaped quotes")]
    public void ParsesQuotedObjectValueWithEscapedQuotes()
    {
        // Arrange
        var input =
"""
text: "say \"hello\""
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
{"text":"say \u0022hello\u0022"}
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "parses quoted object value with leading/trailing spaces")]
    public void ParsesQuotedObjectValueWithLeadingTrailingSpaces()
    {
        // Arrange
        var input =
"""
text: " padded "
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
{"text":" padded "}
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "parses quoted object value with only spaces")]
    public void ParsesQuotedObjectValueWithOnlySpaces()
    {
        // Arrange
        var input =
"""
text: "  "
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
{"text":"  "}
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "parses quoted string value that looks like true")]
    public void ParsesQuotedStringValueThatLooksLikeTrue()
    {
        // Arrange
        var input =
"""
v: "true"
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
{"v":"true"}
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "parses quoted string value that looks like integer")]
    public void ParsesQuotedStringValueThatLooksLikeInteger()
    {
        // Arrange
        var input =
"""
v: "42"
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
{"v":"42"}
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "parses quoted string value that looks like negative decimal")]
    public void ParsesQuotedStringValueThatLooksLikeNegativeDecimal()
    {
        // Arrange
        var input =
"""
v: "-7.5"
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
{"v":"-7.5"}
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "parses quoted key with colon")]
    public void ParsesQuotedKeyWithColon()
    {
        // Arrange
        var input =
"""
"order:id": 7
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
{"order:id":7}
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "parses quoted key with brackets")]
    public void ParsesQuotedKeyWithBrackets()
    {
        // Arrange
        var input =
"""
"[index]": 5
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
{"[index]":5}
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "parses quoted key with braces")]
    public void ParsesQuotedKeyWithBraces()
    {
        // Arrange
        var input =
"""
"{key}": 5
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
{"{key}":5}
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "parses quoted key with comma")]
    public void ParsesQuotedKeyWithComma()
    {
        // Arrange
        var input =
"""
"a,b": 1
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
{"a,b":1}
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "parses quoted key with spaces")]
    public void ParsesQuotedKeyWithSpaces()
    {
        // Arrange
        var input =
"""
"full name": Ada
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
{"full name":"Ada"}
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "parses quoted key with leading hyphen")]
    public void ParsesQuotedKeyWithLeadingHyphen()
    {
        // Arrange
        var input =
"""
"-lead": 1
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
{"-lead":1}
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "parses quoted key with leading and trailing spaces")]
    public void ParsesQuotedKeyWithLeadingAndTrailingSpaces()
    {
        // Arrange
        var input =
"""
" a ": 1
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
{" a ":1}
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "parses quoted numeric key")]
    public void ParsesQuotedNumericKey()
    {
        // Arrange
        var input =
"""
"123": x
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
{"123":"x"}
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "parses quoted empty string key")]
    public void ParsesQuotedEmptyStringKey()
    {
        // Arrange
        var input =
"""
"": 1
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
{"":1}
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "parses dotted keys as identifiers")]
    public void ParsesDottedKeysAsIdentifiers()
    {
        // Arrange
        var input =
"""
user.name: Ada
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
{"user.name":"Ada"}
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "parses underscore-prefixed keys")]
    public void ParsesUnderscorePrefixedKeys()
    {
        // Arrange
        var input =
"""
_private: 1
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
{"_private":1}
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "parses underscore-containing keys")]
    public void ParsesUnderscoreContainingKeys()
    {
        // Arrange
        var input =
"""
user_name: 1
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
{"user_name":1}
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "unescapes newline in key")]
    public void UnescapesNewlineInKey()
    {
        // Arrange
        var input =
"""
"line\nbreak": 1
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
{"line\nbreak":1}
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "unescapes tab in key")]
    public void UnescapesTabInKey()
    {
        // Arrange
        var input =
"""
"tab\there": 2
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
{"tab\there":2}
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "unescapes quotes in key")]
    public void UnescapesQuotesInKey()
    {
        // Arrange
        var input =
"""
"he said \"hi\"": 1
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
{"he said \u0022hi\u0022":1}
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "parses deeply nested objects with indentation")]
    public void ParsesDeeplyNestedObjectsWithIndentation()
    {
        // Arrange
        var input =
"""
a:
  b:
    c: deep
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
{"a":{"b":{"c":"deep"}}}
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

}
