// <auto-generated>
//     This code was generated by DevOp.Toon.SpecGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>


using System;
using System.Collections.Generic;
using System.Text.Json;
using DevOp.Toon;
using Xunit;


namespace DevOp.Toon.Tests.Decode;


[Trait("Category", "decode")]
public class Primitives
{
    [Fact]
    [Trait("Description", "parses safe unquoted string")]
    public void ParsesSafeUnquotedString()
    {
        // Arrange
        var input =
"""
hello
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
"hello"
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "parses unquoted string with underscore and numbers")]
    public void ParsesUnquotedStringWithUnderscoreAndNumbers()
    {
        // Arrange
        var input =
"""
Ada_99
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
"Ada_99"
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "parses empty quoted string")]
    public void ParsesEmptyQuotedString()
    {
        // Arrange
        var input =
"""
""
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = new ToonValue(string.Empty);

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "parses quoted string with newline escape")]
    public void ParsesQuotedStringWithNewlineEscape()
    {
        // Arrange
        var input =
"""
"line1\nline2"
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
"line1\nline2"
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "parses quoted string with tab escape")]
    public void ParsesQuotedStringWithTabEscape()
    {
        // Arrange
        var input =
"""
"tab\there"
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
"tab\there"
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "parses quoted string with carriage return escape")]
    public void ParsesQuotedStringWithCarriageReturnEscape()
    {
        // Arrange
        var input =
"""
"return\rcarriage"
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
"return\rcarriage"
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "parses quoted string with backslash escape")]
    public void ParsesQuotedStringWithBackslashEscape()
    {
        // Arrange
        var input =
"""
"C:\\Users\\path"
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
"C:\\Users\\path"
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "parses quoted string with escaped quotes")]
    public void ParsesQuotedStringWithEscapedQuotes()
    {
        // Arrange
        var input =
"""
"say \"hello\""
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
"say \u0022hello\u0022"
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "parses Unicode string")]
    public void ParsesUnicodeString()
    {
        // Arrange
        var input = "caf\u00E9";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
"caf\u00E9"
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "parses Chinese characters")]
    public void ParsesChineseCharacters()
    {
        // Arrange
        var input = "\u4F60\u597D";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
"\u4F60\u597D"
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "parses emoji")]
    public void ParsesEmoji()
    {
        // Arrange
        var input = "\uD83D\uDE80";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
"\uD83D\uDE80"
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "parses string with emoji and spaces")]
    public void ParsesStringWithEmojiAndSpaces()
    {
        // Arrange
        var input = "hello \uD83D\uDC4B world";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
"hello \uD83D\uDC4B world"
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "parses positive integer")]
    public void ParsesPositiveInteger()
    {
        // Arrange
        var input =
"""
42
""";

        // Act & Assert
        var result = ToonDecoder.Decode<double>(input);

        var expected = 42;

        Assert.Equal(result, expected);
    }

    [Fact]
    [Trait("Description", "parses decimal number")]
    public void ParsesDecimalNumber()
    {
        // Arrange
        var input =
"""
3.14
""";

        // Act & Assert
        var result = ToonDecoder.Decode<double>(input);

        var expected = 3.14;

        Assert.Equal(result, expected);
    }

    [Fact]
    [Trait("Description", "parses negative integer")]
    public void ParsesNegativeInteger()
    {
        // Arrange
        var input =
"""
-7
""";

        // Act & Assert
        var result = ToonDecoder.Decode<double>(input);

        var expected = -7;

        Assert.Equal(result, expected);
    }

    [Fact]
    [Trait("Description", "parses true")]
    public void ParsesTrue()
    {
        // Arrange
        var input =
"""
true
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
true
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "parses false")]
    public void ParsesFalse()
    {
        // Arrange
        var input =
"""
false
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
false
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "parses null")]
    public void ParsesNull()
    {
        // Arrange
        var input =
"""
null
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
null
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "respects ambiguity quoting for true")]
    public void RespectsAmbiguityQuotingForTrue()
    {
        // Arrange
        var input =
"""
"true"
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
"true"
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "respects ambiguity quoting for false")]
    public void RespectsAmbiguityQuotingForFalse()
    {
        // Arrange
        var input =
"""
"false"
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
"false"
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "respects ambiguity quoting for null")]
    public void RespectsAmbiguityQuotingForNull()
    {
        // Arrange
        var input =
"""
"null"
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
"null"
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "respects ambiguity quoting for integer")]
    public void RespectsAmbiguityQuotingForInteger()
    {
        // Arrange
        var input =
"""
"42"
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
"42"
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "respects ambiguity quoting for negative decimal")]
    public void RespectsAmbiguityQuotingForNegativeDecimal()
    {
        // Arrange
        var input =
"""
"-3.14"
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
"-3.14"
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "respects ambiguity quoting for scientific notation")]
    public void RespectsAmbiguityQuotingForScientificNotation()
    {
        // Arrange
        var input =
"""
"1e-6"
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
"1e-6"
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

    [Fact]
    [Trait("Description", "respects ambiguity quoting for leading-zero")]
    public void RespectsAmbiguityQuotingForLeadingZero()
    {
        // Arrange
        var input =
"""
"05"
""";

        // Act & Assert
        var result = ToonDecoder.Decode(input);

        var expected = ToonNode.Parse("""
"05"
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

}
