// <auto-generated>
//     This code was generated by DevOp.Toon.SpecGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>


using System;
using System.Collections.Generic;
using System.Text.Json;
using DevOp.Toon;
using Xunit;


namespace DevOp.Toon.Tests.Decode;


[Trait("Category", "decode")]
public class RootForm
{
    [Fact]
    [Trait("Description", "parses empty document as empty object")]
    public void ParsesEmptyDocumentAsEmptyObject()
    {
        // Arrange
        var input =
"""

""";

        // Act & Assert
        var options = new ToonDecodeOptions
        {
            Indent = 2,
            Strict = true,
        };

        var result = ToonDecoder.Decode(input, options);

        var expected = ToonNode.Parse("""
{}
""");

        Assert.True(ToonNode.DeepEquals(result, expected));
    }

}
