// <auto-generated>
//     This code was generated by DevOp.Toon.SpecGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>


using System;
using System.Collections.Generic;
using System.Text.Json;
using DevOp.Toon;
using Xunit;


namespace DevOp.Toon.Tests.Decode;


[Trait("Category", "decode")]
public class ValidationErrors
{
    [Fact]
    [Trait("Description", "throws on array length mismatch (inline primitives - too many)")]
    public void ThrowsOnArrayLengthMismatchInlinePrimitivesTooMany()
    {
        // Arrange
        var input =
"""
tags[2]: a,b,c
""";

        // Act & Assert
        Assert.Throws<ToonFormatException>(() => ToonDecoder.Decode(input));
    }

    [Fact]
    [Trait("Description", "throws on array length mismatch (list format - too many)")]
    public void ThrowsOnArrayLengthMismatchListFormatTooMany()
    {
        // Arrange
        var input =
"""
items[1]:
  - 1
  - 2
""";

        // Act & Assert
        Assert.Throws<ToonFormatException>(() => ToonDecoder.Decode(input));
    }

    [Fact]
    [Trait("Description", "throws on tabular row value count mismatch with header field count")]
    public void ThrowsOnTabularRowValueCountMismatchWithHeaderFieldCount()
    {
        // Arrange
        var input =
"""
items[2]{id,name}:
  1,Ada
  2
""";

        // Act & Assert
        Assert.Throws<ToonFormatException>(() => ToonDecoder.Decode(input));
    }

    [Fact]
    [Trait("Description", "throws on tabular row count mismatch with header length")]
    public void ThrowsOnTabularRowCountMismatchWithHeaderLength()
    {
        // Arrange
        var input =
"""
[1]{id}:
  1
  2
""";

        // Act & Assert
        Assert.Throws<ToonFormatException>(() => ToonDecoder.Decode(input));
    }

    [Fact]
    [Trait("Description", "throws on invalid escape sequence")]
    public void ThrowsOnInvalidEscapeSequence()
    {
        // Arrange
        var input =
"""
"a\x"
""";

        // Act & Assert
        Assert.Throws<ToonFormatException>(() => ToonDecoder.Decode(input));
    }

    [Fact]
    [Trait("Description", "throws on unterminated string")]
    public void ThrowsOnUnterminatedString()
    {
        // Arrange
        var input =
"""
"unterminated
""";

        // Act & Assert
        Assert.Throws<ToonFormatException>(() => ToonDecoder.Decode(input));
    }

    [Fact]
    [Trait("Description", "throws on missing colon in key-value context")]
    public void ThrowsOnMissingColonInKeyValueContext()
    {
        // Arrange
        var input =
"""
a:
  user
""";

        // Act & Assert
        Assert.Throws<ToonFormatException>(() => ToonDecoder.Decode(input));
    }

    [Fact]
    [Trait("Description", "throws on two primitives at root depth in strict mode")]
    public void ThrowsOnTwoPrimitivesAtRootDepthInStrictMode()
    {
        // Arrange
        var input =
"""
hello
world
""";

        // Act & Assert
        var options = new ToonDecodeOptions
        {
            Indent = 2,
            Strict = true,
        };

        Assert.Throws<ToonFormatException>(() => ToonDecoder.Decode(input, options));
    }

    [Fact]
    [Trait("Description", "throws on delimiter mismatch (header declares tab, row uses comma)")]
    public void ThrowsOnDelimiterMismatchHeaderDeclaresTabRowUsesComma()
    {
        // Arrange
        var input =
"""
items[2	]{a	b}:
  1,2
  3,4
""";

        // Act & Assert
        Assert.Throws<ToonFormatException>(() => ToonDecoder.Decode(input));
    }

    [Fact]
    [Trait("Description", "throws on mismatched delimiter between bracket and brace fields")]
    public void ThrowsOnMismatchedDelimiterBetweenBracketAndBraceFields()
    {
        // Arrange
        var input =
"""
items[2	]{a,b}:
  1	2
  3	4
""";

        // Act & Assert
        var options = new ToonDecodeOptions
        {
            Indent = 2,
            Strict = true,
        };

        Assert.Throws<ToonFormatException>(() => ToonDecoder.Decode(input, options));
    }

}
