// <auto-generated>
//     This code was generated by DevOp.Toon.SpecGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>


using System;
using System.Collections.Generic;
using System.Text.Json;
using DevOp.Toon;
using Xunit;


namespace DevOp.Toon.Tests.Encode;


[Trait("Category", "encode")]
public class ArraysNested
{
    [Fact]
    [Trait("Description", "encodes nested arrays of primitives")]
    public void EncodesNestedArraysOfPrimitives()
    {
        // Arrange
        var input =
            new
            {
                @pairs =new object[] {                
                    new object[] {                    
                        @"a",
                        @"b",
                    }
                    ,
                    new object[] {                    
                        @"c",
                        @"d",
                    }
                    ,
                }
,
            }
            ;

        var expected =
"""
pairs[2]:
  - [2]: a,b
  - [2]: c,d
""";

        // Act & Assert
        var result = ToonEncoder.Encode(input, new LegacyDefaultToonEncodeOptions());

        Assert.Equal(expected, result);
    }

    [Fact]
    [Trait("Description", "quotes strings containing delimiters in nested arrays")]
    public void QuotesStringsContainingDelimitersInNestedArrays()
    {
        // Arrange
        var input =
            new
            {
                @pairs =new object[] {                
                    new object[] {                    
                        @"a",
                        @"b",
                    }
                    ,
                    new object[] {                    
                        @"c,d",
                        @"e:f",
                        @"true",
                    }
                    ,
                }
,
            }
            ;

        var expected =
"""
pairs[2]:
  - [2]: a,b
  - [3]: "c,d","e:f","true"
""";

        // Act & Assert
        var result = ToonEncoder.Encode(input, new LegacyDefaultToonEncodeOptions());

        Assert.Equal(expected, result);
    }

    [Fact]
    [Trait("Description", "encodes empty inner arrays")]
    public void EncodesEmptyInnerArrays()
    {
        // Arrange
        var input =
            new
            {
                @pairs =new object[] {                
                    new object[] {                    
                    }
                    ,
                    new object[] {                    
                    }
                    ,
                }
,
            }
            ;

        var expected =
"""
pairs[2]:
  - [0]:
  - [0]:
""";

        // Act & Assert
        var result = ToonEncoder.Encode(input, new LegacyDefaultToonEncodeOptions());

        Assert.Equal(expected, result);
    }

    [Fact]
    [Trait("Description", "encodes mixed-length inner arrays")]
    public void EncodesMixedLengthInnerArrays()
    {
        // Arrange
        var input =
            new
            {
                @pairs =new object[] {                
                    new object[] {                    
                        1,
                    }
                    ,
                    new object[] {                    
                        2,
                        3,
                    }
                    ,
                }
,
            }
            ;

        var expected =
"""
pairs[2]:
  - [1]: 1
  - [2]: 2,3
""";

        // Act & Assert
        var result = ToonEncoder.Encode(input, new LegacyDefaultToonEncodeOptions());

        Assert.Equal(expected, result);
    }

    [Fact]
    [Trait("Description", "encodes root-level primitive array")]
    public void EncodesRootLevelPrimitiveArray()
    {
        // Arrange
        var input =
            new object[] {            
                @"x",
                @"y",
                @"true",
                true,
                10,
            }
            ;

        var expected =
"""
[5]: x,y,"true",true,10
""";

        // Act & Assert
        var result = ToonEncoder.Encode(input, new LegacyDefaultToonEncodeOptions());

        Assert.Equal(expected, result);
    }

    [Fact]
    [Trait("Description", "encodes root-level array of uniform objects in tabular format")]
    public void EncodesRootLevelArrayOfUniformObjectsInTabularFormat()
    {
        // Arrange
        var input =
            new object[] {            
                new
                {
                    @id = 1,
                }
                ,
                new
                {
                    @id = 2,
                }
                ,
            }
            ;

        var expected =
"""
[2]{id}:
  1
  2
""";

        // Act & Assert
        var result = ToonEncoder.Encode(input, new LegacyDefaultToonEncodeOptions());

        Assert.Equal(expected, result);
    }

    [Fact]
    [Trait("Description", "encodes root-level array of non-uniform objects in list format")]
    public void EncodesRootLevelArrayOfNonUniformObjectsInListFormat()
    {
        // Arrange
        var input =
            new object[] {            
                new
                {
                    @id = 1,
                }
                ,
                new
                {
                    @id = 2,
                    @name = @"Ada",
                }
                ,
            }
            ;

        var expected =
"""
[2]:
  - id: 1
  - id: 2
    name: Ada
""";

        // Act & Assert
        var result = ToonEncoder.Encode(input, new LegacyToonEncodeOptions());

        Assert.Equal(expected, result);
    }

    [Fact]
    [Trait("Description", "encodes root-level array mixing primitive, object, and array of objects in list format")]
    public void EncodesRootLevelArrayMixingPrimitiveObjectAndArrayOfObjectsInListFormat()
    {
        // Arrange
        var input =
            new object[] {            
                @"summary",
                new
                {
                    @id = 1,
                    @name = @"Ada",
                }
                ,
                new object[] {                
                    new
                    {
                        @id = 2,
                    }
                    ,
                    new
                    {
                        @status = @"draft",
                    }
                    ,
                }
                ,
            }
            ;

        var expected =
"""
[3]:
  - summary
  - id: 1
    name: Ada
  - [2]:
    - id: 2
    - status: draft
""";

        // Act & Assert
        var result = ToonEncoder.Encode(input, new LegacyDefaultToonEncodeOptions());

        Assert.Equal(expected, result);
    }

    [Fact]
    [Trait("Description", "encodes root-level arrays of arrays")]
    public void EncodesRootLevelArraysOfArrays()
    {
        // Arrange
        var input =
            new object[] {            
                new object[] {                
                    1,
                    2,
                }
                ,
                new object[] {                
                }
                ,
            }
            ;

        var expected =
"""
[2]:
  - [2]: 1,2
  - [0]:
""";

        // Act & Assert
        var result = ToonEncoder.Encode(input, new LegacyDefaultToonEncodeOptions());

        Assert.Equal(expected, result);
    }

    [Fact]
    [Trait("Description", "encodes empty root-level array")]
    public void EncodesEmptyRootLevelArray()
    {
        // Arrange
        var input =
            new object[] {            
            }
            ;

        var expected =
"""
[0]:
""";

        // Act & Assert
        var result = ToonEncoder.Encode(input, new LegacyDefaultToonEncodeOptions());

        Assert.Equal(expected, result);
    }

    [Fact]
    [Trait("Description", "encodes complex nested structure")]
    public void EncodesComplexNestedStructure()
    {
        // Arrange
        var input =
            new
            {
                @user =
                new
                {
                    @id = 123,
                    @name = @"Ada",
                    @tags =new object[] {                    
                        @"reading",
                        @"gaming",
                    }
,
                    @active = true,
                    @prefs =new object[] {                    
                    }
,
                }
,
            }
            ;

        var expected =
"""
user:
  id: 123
  name: Ada
  tags[2]: reading,gaming
  active: true
""";

        // Act & Assert
        var result = ToonEncoder.Encode(input, new LegacyDefaultToonEncodeOptions());

        Assert.Equal(expected, result);
    }

    [Fact]
    [Trait("Description", "uses list format for arrays mixing primitives and objects")]
    public void UsesListFormatForArraysMixingPrimitivesAndObjects()
    {
        // Arrange
        var input =
            new
            {
                @items =new object[] {                
                    1,
                    new
                    {
                        @a = 1,
                    }
                    ,
                    @"text",
                }
,
            }
            ;

        var expected =
"""
items[3]:
  - 1
  - a: 1
  - text
""";

        // Act & Assert
        var result = ToonEncoder.Encode(input, new LegacyDefaultToonEncodeOptions());

        Assert.Equal(expected, result);
    }

    [Fact]
    [Trait("Description", "uses list format for arrays mixing objects and arrays")]
    public void UsesListFormatForArraysMixingObjectsAndArrays()
    {
        // Arrange
        var input =
            new
            {
                @items =new object[] {                
                    new
                    {
                        @a = 1,
                    }
                    ,
                    new object[] {                    
                        1,
                        2,
                    }
                    ,
                }
,
            }
            ;

        var expected =
"""
items[2]:
  - a: 1
  - [2]: 1,2
""";

        // Act & Assert
        var result = ToonEncoder.Encode(input, new LegacyDefaultToonEncodeOptions());

        Assert.Equal(expected, result);
    }

}
