// <auto-generated>
//     This code was generated by DevOp.Toon.SpecGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>


using System;
using System.Collections.Generic;
using System.Text.Json;
using DevOp.Toon;
using Xunit;


namespace DevOp.Toon.Tests.Encode;


[Trait("Category", "encode")]
public class ArraysTabular
{
    [Fact]
    [Trait("Description", "encodes arrays of uniform objects in tabular format")]
    public void EncodesArraysOfUniformObjectsInTabularFormat()
    {
        // Arrange
        var input =
            new
            {
                @items =new object[] {                
                    new
                    {
                        @sku = @"A1",
                        @qty = 2,
                        @price = 9.99,
                    }
                    ,
                    new
                    {
                        @sku = @"B2",
                        @qty = 1,
                        @price = 14.5,
                    }
                    ,
                }
,
            }
            ;

        var expected =
"""
items[2]{sku,qty,price}:
  A1,2,9.99
  B2,1,14.5
""";

        // Act & Assert
        var result = ToonEncoder.Encode(input);

        Assert.Equal(expected, result);
    }

    [Fact]
    [Trait("Description", "encodes null values in tabular format")]
    public void EncodesNullValuesInTabularFormat()
    {
        // Arrange
        var input =
            new
            {
                @items =new object[] {                
                    new
                    {
                        @id = 1,
                        @value = (string)null,                    }
                    ,
                    new
                    {
                        @id = 2,
                        @value = @"test",
                    }
                    ,
                }
,
            }
            ;

        var expected =
"""
items[2]{id,value}:
  1,null
  2,test
""";

        // Act & Assert
        var result = ToonEncoder.Encode(input);

        Assert.Equal(expected, result);
    }

    [Fact]
    [Trait("Description", "quotes strings containing delimiters in tabular rows")]
    public void QuotesStringsContainingDelimitersInTabularRows()
    {
        // Arrange
        var input =
            new
            {
                @items =new object[] {                
                    new
                    {
                        @sku = @"A,1",
                        @desc = @"cool",
                        @qty = 2,
                    }
                    ,
                    new
                    {
                        @sku = @"B2",
                        @desc = @"wip: test",
                        @qty = 1,
                    }
                    ,
                }
,
            }
            ;

        var expected =
"""
items[2]{sku,desc,qty}:
  "A,1",cool,2
  B2,"wip: test",1
""";

        // Act & Assert
        var result = ToonEncoder.Encode(input);

        Assert.Equal(expected, result);
    }

    [Fact]
    [Trait("Description", "quotes ambiguous strings in tabular rows")]
    public void QuotesAmbiguousStringsInTabularRows()
    {
        // Arrange
        var input =
            new
            {
                @items =new object[] {                
                    new
                    {
                        @id = 1,
                        @status = @"true",
                    }
                    ,
                    new
                    {
                        @id = 2,
                        @status = @"false",
                    }
                    ,
                }
,
            }
            ;

        var expected =
"""
items[2]{id,status}:
  1,"true"
  2,"false"
""";

        // Act & Assert
        var result = ToonEncoder.Encode(input);

        Assert.Equal(expected, result);
    }

}
