// <auto-generated>
//     This code was generated by DevOp.Toon.SpecGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>


using System;
using System.Collections.Generic;
using System.Text.Json;
using DevOp.Toon;
using Xunit;


namespace DevOp.Toon.Tests.Encode;


[Trait("Category", "encode")]
public class ArraysObjects
{
    [Fact]
    [Trait("Description", "uses list format for objects with different fields")]
    public void UsesListFormatForObjectsWithDifferentFields()
    {
        // Arrange
        var input =
            new
            {
                @items =new object[] {                
                    new
                    {
                        @id = 1,
                        @name = @"First",
                    }
                    ,
                    new
                    {
                        @id = 2,
                        @name = @"Second",
                        @extra = true,
                    }
                    ,
                }
,
            }
            ;

        var expected =
"""
items[2]:
  - id: 1
    name: First
  - id: 2
    name: Second
    extra: true
""";

        // Act & Assert
        var result = ToonEncoder.Encode(input, new LegacyToonEncodeOptions());

        Assert.Equal(expected, result);
    }

    [Fact]
    [Trait("Description", "uses list format for objects with nested values")]
    public void UsesListFormatForObjectsWithNestedValues()
    {
        // Arrange
        var input =
            new
            {
                @items =new object[] {                
                    new
                    {
                        @id = 1,
                        @nested =
                        new
                        {
                            @x = 1,
                        }
,
                    }
                    ,
                }
,
            }
            ;

        var expected =
"""
items[1]:
  - id: 1
    nested:
      x: 1
""";

        // Act & Assert
        var result = ToonEncoder.Encode(input, new LegacyToonEncodeOptions());

        Assert.Equal(expected, result);
    }

    [Fact]
    [Trait("Description", "preserves field order in list items - array first")]
    public void PreservesFieldOrderInListItemsArrayFirst()
    {
        // Arrange
        var input =
            new
            {
                @items =new object[] {                
                    new
                    {
                        @nums =new object[] {                        
                            1,
                            2,
                            3,
                        }
,
                        @name = @"Ada",
                    }
                    ,
                }
,
            }
            ;

        var expected =
"""
items[1]:
  - nums[3]: 1,2,3
    name: Ada
""";

        // Act & Assert
        var result = ToonEncoder.Encode(input, new LegacyToonEncodeOptions());

        Assert.Equal(expected, result);
    }

    [Fact]
    [Trait("Description", "preserves field order in list items - primitive first")]
    public void PreservesFieldOrderInListItemsPrimitiveFirst()
    {
        // Arrange
        var input =
            new
            {
                @items =new object[] {                
                    new
                    {
                        @name = @"Ada",
                        @nums =new object[] {                        
                            1,
                            2,
                            3,
                        }
,
                    }
                    ,
                }
,
            }
            ;

        var expected =
"""
items[1]:
  - name: Ada
    nums[3]: 1,2,3
""";

        // Act & Assert
        var result = ToonEncoder.Encode(input, new LegacyToonEncodeOptions());

        Assert.Equal(expected, result);
    }

    [Fact]
    [Trait("Description", "uses list format for objects containing arrays of arrays")]
    public void UsesListFormatForObjectsContainingArraysOfArrays()
    {
        // Arrange
        var input =
            new
            {
                @items =new object[] {                
                    new
                    {
                        @matrix =new object[] {                        
                            new object[] {                            
                                1,
                                2,
                            }
                            ,
                            new object[] {                            
                                3,
                                4,
                            }
                            ,
                        }
,
                        @name = @"grid",
                    }
                    ,
                }
,
            }
            ;

        var expected =
"""
items[1]:
  - matrix[2]:
      - [2]: 1,2
      - [2]: 3,4
    name: grid
""";

        // Act & Assert
        var result = ToonEncoder.Encode(input, new LegacyToonEncodeOptions());

        Assert.Equal(expected, result);
    }

    [Fact]
    [Trait("Description", "uses tabular format for nested uniform object arrays")]
    public void UsesTabularFormatForNestedUniformObjectArrays()
    {
        // Arrange
        var input =
            new
            {
                @items =new object[] {                
                    new
                    {
                        @users =new object[] {                        
                            new
                            {
                                @id = 1,
                                @name = @"Ada",
                            }
                            ,
                            new
                            {
                                @id = 2,
                                @name = @"Bob",
                            }
                            ,
                        }
,
                        @status = @"active",
                    }
                    ,
                }
,
            }
            ;

        var expected =
"""
items[1]:
  - users[2]{id,name}:
      1,Ada
      2,Bob
    status: active
""";

        // Act & Assert
        var result = ToonEncoder.Encode(input, new LegacyToonEncodeOptions());

        Assert.Equal(expected, result);
    }

    [Fact]
    [Trait("Description", "uses list format for nested object arrays with mismatched keys")]
    public void UsesListFormatForNestedObjectArraysWithMismatchedKeys()
    {
        // Arrange
        var input =
            new
            {
                @items =new object[] {                
                    new
                    {
                        @users =new object[] {                        
                            new
                            {
                                @id = 1,
                                @name = @"Ada",
                            }
                            ,
                            new
                            {
                                @id = 2,
                            }
                            ,
                        }
,
                        @status = @"active",
                    }
                    ,
                }
,
            }
            ;

        var expected =
"""
items[1]:
  - users[2]:
      - id: 1
        name: Ada
      - id: 2
    status: active
""";

        // Act & Assert
        var result = ToonEncoder.Encode(input, new LegacyToonEncodeOptions());

        Assert.Equal(expected, result);
    }

    [Fact]
    [Trait("Description", "uses list format for objects with multiple array fields")]
    public void UsesListFormatForObjectsWithMultipleArrayFields()
    {
        // Arrange
        var input =
            new
            {
                @items =new object[] {                
                    new
                    {
                        @nums =new object[] {                        
                            1,
                            2,
                        }
,
                        @tags =new object[] {                        
                            @"a",
                            @"b",
                        }
,
                        @name = @"test",
                    }
                    ,
                }
,
            }
            ;

        var expected =
"""
items[1]:
  - nums[2]: 1,2
    tags[2]: a,b
    name: test
""";

        // Act & Assert
        var result = ToonEncoder.Encode(input, new LegacyToonEncodeOptions());

        Assert.Equal(expected, result);
    }

    [Fact]
    [Trait("Description", "uses list format for objects with only array fields")]
    public void UsesListFormatForObjectsWithOnlyArrayFields()
    {
        // Arrange
        var input =
            new
            {
                @items =new object[] {                
                    new
                    {
                        @nums =new object[] {                        
                            1,
                            2,
                            3,
                        }
,
                        @tags =new object[] {                        
                            @"a",
                            @"b",
                        }
,
                    }
                    ,
                }
,
            }
            ;

        var expected =
"""
items[1]:
  - nums[3]: 1,2,3
    tags[2]: a,b
""";

        // Act & Assert
        var result = ToonEncoder.Encode(input, new LegacyDefaultToonEncodeOptions());

        Assert.Equal(expected, result);
    }

    [Fact]
    [Trait("Description", "encodes objects with empty arrays in list format")]
    public void EncodesObjectsWithEmptyArraysInListFormat()
    {
        // Arrange
        var input =
            new
            {
                @items =new object[] {                
                    new
                    {
                        @name = @"Ada",
                        @data =new object[] {                        
                        }
,
                    }
                    ,
                }
,
            }
            ;

        var expected =
"""
items[1]:
  - name: Ada
""";

        // Act & Assert
        var result = ToonEncoder.Encode(input, new LegacyToonEncodeOptions());

        Assert.Equal(expected, result);
    }

    [Fact]
    [Trait("Description", "uses canonical encoding for multi-field list-item objects with tabular arrays")]
    public void UsesCanonicalEncodingForMultiFieldListItemObjectsWithTabularArrays()
    {
        // Arrange
        var input =
            new
            {
                @items =new object[] {                
                    new
                    {
                        @users =new object[] {                        
                            new
                            {
                                @id = 1,
                            }
                            ,
                            new
                            {
                                @id = 2,
                            }
                            ,
                        }
,
                        @note = @"x",
                    }
                    ,
                }
,
            }
            ;

        var expected =
"""
items[1]:
  - users[2]{id}:
      1
      2
    note: x
""";

        // Act & Assert
        var result = ToonEncoder.Encode(input, new LegacyToonEncodeOptions());

        Assert.Equal(expected, result);
    }

    [Fact]
    [Trait("Description", "uses canonical encoding for single-field list-item tabular arrays")]
    public void UsesCanonicalEncodingForSingleFieldListItemTabularArrays()
    {
        // Arrange
        var input =
            new
            {
                @items =new object[] {                
                    new
                    {
                        @users =new object[] {                        
                            new
                            {
                                @id = 1,
                                @name = @"Ada",
                            }
                            ,
                            new
                            {
                                @id = 2,
                                @name = @"Bob",
                            }
                            ,
                        }
,
                    }
                    ,
                }
,
            }
            ;

        var expected =
"""
items[1]:
  - users[2]{id,name}:
      1,Ada
      2,Bob
""";

        // Act & Assert
        var result = ToonEncoder.Encode(input, new LegacyDefaultToonEncodeOptions());

        Assert.Equal(expected, result);
    }

    [Fact]
    [Trait("Description", "places empty arrays on hyphen line when first")]
    public void PlacesEmptyArraysOnHyphenLineWhenFirst()
    {
        // Arrange
        var input =
            new
            {
                @items =new object[] {                
                    new
                    {
                        @data =new object[] {                        
                        }
,
                        @name = @"x",
                    }
                    ,
                }
,
            }
            ;

        var expected =
"""
items[1]:
  - data[0]:
    name: x
""";

        // Act & Assert
        var result = ToonEncoder.Encode(input, new LegacyToonEncodeOptions());

        Assert.Equal(expected, result);
    }

    [Fact]
    [Trait("Description", "encodes empty object list items as bare hyphen")]
    public void EncodesEmptyObjectListItemsAsBareHyphen()
    {
        // Arrange
        var input =
            new
            {
                @items =new object[] {                
                    @"first",
                    @"second",
                    new
                    {
                    }
                    ,
                }
,
            }
            ;

        var expected =
"""
items[3]:
  - first
  - second
  -
""";

        // Act & Assert
        var result = ToonEncoder.Encode(input, new LegacyDefaultToonEncodeOptions());

        Assert.Equal(expected, result);
    }

    [Fact]
    [Trait("Description", "uses field order from first object for tabular headers")]
    public void UsesFieldOrderFromFirstObjectForTabularHeaders()
    {
        // Arrange
        var input =
            new
            {
                @items =new object[] {                
                    new
                    {
                        @a = 1,
                        @b = 2,
                        @c = 3,
                    }
                    ,
                    new
                    {
                        @c = 30,
                        @b = 20,
                        @a = 10,
                    }
                    ,
                }
,
            }
            ;

        var expected =
"""
items[2]{a,b,c}:
  1,2,3
  10,20,30
""";

        // Act & Assert
        var result = ToonEncoder.Encode(input, new LegacyDefaultToonEncodeOptions());

        Assert.Equal(expected, result);
    }

    [Fact]
    [Trait("Description", "uses list format when one object has nested field")]
    public void UsesListFormatWhenOneObjectHasNestedField()
    {
        // Arrange
        var input =
            new
            {
                @items =new object[] {                
                    new
                    {
                        @id = 1,
                        @data = @"string",
                    }
                    ,
                    new
                    {
                        @id = 2,
                        @data =
                        new
                        {
                            @nested = true,
                        }
,
                    }
                    ,
                }
,
            }
            ;

        var expected =
"""
items[2]:
  - id: 1
    data: string
  - id: 2
    data:
      nested: true
""";

        // Act & Assert
        var result = ToonEncoder.Encode(input, new LegacyToonEncodeOptions());

        Assert.Equal(expected, result);
    }

}
