// <auto-generated>
//     This code was generated by DevOp.Toon.SpecGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>


using System;
using System.Collections.Generic;
using System.Text.Json;
using DevOp.Toon;
using Xunit;


namespace DevOp.Toon.Tests.Encode;


[Trait("Category", "encode")]
public class ArraysPrimitive
{
    [Fact]
    [Trait("Description", "encodes string arrays inline")]
    public void EncodesStringArraysInline()
    {
        // Arrange
        var input =
            new
            {
                @tags =new object[] {                
                    @"reading",
                    @"gaming",
                }
,
            }
            ;

        var expected =
"""
tags[2]: reading,gaming
""";

        // Act & Assert
        var result = ToonEncoder.Encode(input);

        Assert.Equal(expected, result);
    }

    [Fact]
    [Trait("Description", "encodes number arrays inline")]
    public void EncodesNumberArraysInline()
    {
        // Arrange
        var input =
            new
            {
                @nums =new object[] {                
                    1,
                    2,
                    3,
                }
,
            }
            ;

        var expected =
"""
nums[3]: 1,2,3
""";

        // Act & Assert
        var result = ToonEncoder.Encode(input);

        Assert.Equal(expected, result);
    }

    [Fact]
    [Trait("Description", "encodes mixed primitive arrays inline")]
    public void EncodesMixedPrimitiveArraysInline()
    {
        // Arrange
        var input =
            new
            {
                @data =new object[] {                
                    @"x",
                    @"y",
                    true,
                    10,
                }
,
            }
            ;

        var expected =
"""
data[4]: x,y,true,10
""";

        // Act & Assert
        var result = ToonEncoder.Encode(input);

        Assert.Equal(expected, result);
    }

    [Fact]
    [Trait("Description", "encodes empty arrays")]
    public void EncodesEmptyArrays()
    {
        // Arrange
        var input =
            new
            {
                @items =new object[] {                
                }
,
            }
            ;

        var expected = "";

        // Act & Assert
        var result = ToonEncoder.Encode(input);

        Assert.Equal(expected, result);
    }

    [Fact]
    [Trait("Description", "encodes empty string in single-item array")]
    public void EncodesEmptyStringInSingleItemArray()
    {
        // Arrange
        var input =
            new
            {
                @items =new object[] {                
                    @"",
                }
,
            }
            ;

        var expected =
"""
items[1]: ""
""";

        // Act & Assert
        var result = ToonEncoder.Encode(input);

        Assert.Equal(expected, result);
    }

    [Fact]
    [Trait("Description", "encodes empty string in multi-item array")]
    public void EncodesEmptyStringInMultiItemArray()
    {
        // Arrange
        var input =
            new
            {
                @items =new object[] {                
                    @"a",
                    @"",
                    @"b",
                }
,
            }
            ;

        var expected =
"""
items[3]: a,"",b
""";

        // Act & Assert
        var result = ToonEncoder.Encode(input);

        Assert.Equal(expected, result);
    }

    [Fact]
    [Trait("Description", "encodes whitespace-only strings in arrays")]
    public void EncodesWhitespaceOnlyStringsInArrays()
    {
        // Arrange
        var input =
            new
            {
                @items =new object[] {                
                    @" ",
                    @"  ",
                }
,
            }
            ;

        var expected =
"""
items[2]: " ","  "
""";

        // Act & Assert
        var result = ToonEncoder.Encode(input);

        Assert.Equal(expected, result);
    }

    [Fact]
    [Trait("Description", "quotes array strings with comma")]
    public void QuotesArrayStringsWithComma()
    {
        // Arrange
        var input =
            new
            {
                @items =new object[] {                
                    @"a",
                    @"b,c",
                    @"d:e",
                }
,
            }
            ;

        var expected =
"""
items[3]: a,"b,c","d:e"
""";

        // Act & Assert
        var result = ToonEncoder.Encode(input);

        Assert.Equal(expected, result);
    }

    [Fact]
    [Trait("Description", "quotes strings that look like booleans in arrays")]
    public void QuotesStringsThatLookLikeBooleansInArrays()
    {
        // Arrange
        var input =
            new
            {
                @items =new object[] {                
                    @"x",
                    @"true",
                    @"42",
                    @"-3.14",
                }
,
            }
            ;

        var expected =
"""
items[4]: x,"true","42","-3.14"
""";

        // Act & Assert
        var result = ToonEncoder.Encode(input);

        Assert.Equal(expected, result);
    }

    [Fact]
    [Trait("Description", "quotes strings with structural meanings in arrays")]
    public void QuotesStringsWithStructuralMeaningsInArrays()
    {
        // Arrange
        var input =
            new
            {
                @items =new object[] {                
                    @"[5]",
                    @"- item",
                    @"{key}",
                }
,
            }
            ;

        var expected =
"""
items[3]: "[5]","- item","{key}"
""";

        // Act & Assert
        var result = ToonEncoder.Encode(input);

        Assert.Equal(expected, result);
    }

}
