// <auto-generated>
//     This code was generated by DevOp.Toon.SpecGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>


using System;
using System.Collections.Generic;
using System.Text.Json;
using DevOp.Toon;
using Xunit;


namespace DevOp.Toon.Tests.Encode;


[Trait("Category", "encode")]
public class Delimiters
{
    [Fact]
    [Trait("Description", "encodes primitive arrays with tab delimiter")]
    public void EncodesPrimitiveArraysWithTabDelimiter()
    {
        // Arrange
        var input =
            new
            {
                @tags =new object[] {                
                    @"reading",
                    @"gaming",
                    @"coding",
                }
,
            }
            ;

        var expected =
"""
tags[3	]: reading	gaming	coding
""";

        // Act & Assert
        var options = new LegacyToonEncodeOptions
        {
            Delimiter = ToonDelimiter.TAB,
        };

        var result = ToonEncoder.Encode(input, options);

        Assert.Equal(expected, result);
    }

    [Fact]
    [Trait("Description", "encodes primitive arrays with pipe delimiter")]
    public void EncodesPrimitiveArraysWithPipeDelimiter()
    {
        // Arrange
        var input =
            new
            {
                @tags =new object[] {                
                    @"reading",
                    @"gaming",
                    @"coding",
                }
,
            }
            ;

        var expected =
"""
tags[3|]: reading|gaming|coding
""";

        // Act & Assert
        var options = new LegacyToonEncodeOptions
        {
            Delimiter = ToonDelimiter.PIPE,
        };

        var result = ToonEncoder.Encode(input, options);

        Assert.Equal(expected, result);
    }

    [Fact]
    [Trait("Description", "encodes primitive arrays with comma delimiter")]
    public void EncodesPrimitiveArraysWithCommaDelimiter()
    {
        // Arrange
        var input =
            new
            {
                @tags =new object[] {                
                    @"reading",
                    @"gaming",
                    @"coding",
                }
,
            }
            ;

        var expected =
"""
tags[3]: reading,gaming,coding
""";

        // Act & Assert
        var options = new LegacyToonEncodeOptions
        {
            Delimiter = ToonDelimiter.COMMA,
        };

        var result = ToonEncoder.Encode(input, options);

        Assert.Equal(expected, result);
    }

    [Fact]
    [Trait("Description", "encodes tabular arrays with tab delimiter")]
    public void EncodesTabularArraysWithTabDelimiter()
    {
        // Arrange
        var input =
            new
            {
                @items =new object[] {                
                    new
                    {
                        @sku = @"A1",
                        @qty = 2,
                        @price = 9.99,
                    }
                    ,
                    new
                    {
                        @sku = @"B2",
                        @qty = 1,
                        @price = 14.5,
                    }
                    ,
                }
,
            }
            ;

        var expected =
"""
items[2	]{sku	qty	price}:
  A1	2	9.99
  B2	1	14.5
""";

        // Act & Assert
        var options = new LegacyToonEncodeOptions
        {
            Delimiter = ToonDelimiter.TAB,
        };

        var result = ToonEncoder.Encode(input, options);

        Assert.Equal(expected, result);
    }

    [Fact]
    [Trait("Description", "encodes tabular arrays with pipe delimiter")]
    public void EncodesTabularArraysWithPipeDelimiter()
    {
        // Arrange
        var input =
            new
            {
                @items =new object[] {                
                    new
                    {
                        @sku = @"A1",
                        @qty = 2,
                        @price = 9.99,
                    }
                    ,
                    new
                    {
                        @sku = @"B2",
                        @qty = 1,
                        @price = 14.5,
                    }
                    ,
                }
,
            }
            ;

        var expected =
"""
items[2|]{sku|qty|price}:
  A1|2|9.99
  B2|1|14.5
""";

        // Act & Assert
        var options = new LegacyToonEncodeOptions
        {
            Delimiter = ToonDelimiter.PIPE,
        };

        var result = ToonEncoder.Encode(input, options);

        Assert.Equal(expected, result);
    }

    [Fact]
    [Trait("Description", "encodes nested arrays with tab delimiter")]
    public void EncodesNestedArraysWithTabDelimiter()
    {
        // Arrange
        var input =
            new
            {
                @pairs =new object[] {                
                    new object[] {                    
                        @"a",
                        @"b",
                    }
                    ,
                    new object[] {                    
                        @"c",
                        @"d",
                    }
                    ,
                }
,
            }
            ;

        var expected =
"""
pairs[2	]:
  - [2	]: a	b
  - [2	]: c	d
""";

        // Act & Assert
        var options = new LegacyToonEncodeOptions
        {
            Delimiter = ToonDelimiter.TAB,
        };

        var result = ToonEncoder.Encode(input, options);

        Assert.Equal(expected, result);
    }

    [Fact]
    [Trait("Description", "encodes nested arrays with pipe delimiter")]
    public void EncodesNestedArraysWithPipeDelimiter()
    {
        // Arrange
        var input =
            new
            {
                @pairs =new object[] {                
                    new object[] {                    
                        @"a",
                        @"b",
                    }
                    ,
                    new object[] {                    
                        @"c",
                        @"d",
                    }
                    ,
                }
,
            }
            ;

        var expected =
"""
pairs[2|]:
  - [2|]: a|b
  - [2|]: c|d
""";

        // Act & Assert
        var options = new LegacyToonEncodeOptions
        {
            Delimiter = ToonDelimiter.PIPE,
        };

        var result = ToonEncoder.Encode(input, options);

        Assert.Equal(expected, result);
    }

    [Fact]
    [Trait("Description", "encodes root-level array with tab delimiter")]
    public void EncodesRootLevelArrayWithTabDelimiter()
    {
        // Arrange
        var input =
            new object[] {            
                @"x",
                @"y",
                @"z",
            }
            ;

        var expected =
"""
[3	]: x	y	z
""";

        // Act & Assert
        var options = new LegacyToonEncodeOptions
        {
            Delimiter = ToonDelimiter.TAB,
        };

        var result = ToonEncoder.Encode(input, options);

        Assert.Equal(expected, result);
    }

    [Fact]
    [Trait("Description", "encodes root-level array with pipe delimiter")]
    public void EncodesRootLevelArrayWithPipeDelimiter()
    {
        // Arrange
        var input =
            new object[] {            
                @"x",
                @"y",
                @"z",
            }
            ;

        var expected =
"""
[3|]: x|y|z
""";

        // Act & Assert
        var options = new LegacyToonEncodeOptions
        {
            Delimiter = ToonDelimiter.PIPE,
        };

        var result = ToonEncoder.Encode(input, options);

        Assert.Equal(expected, result);
    }

    [Fact]
    [Trait("Description", "encodes root-level array of objects with tab delimiter")]
    public void EncodesRootLevelArrayOfObjectsWithTabDelimiter()
    {
        // Arrange
        var input =
            new object[] {            
                new
                {
                    @id = 1,
                }
                ,
                new
                {
                    @id = 2,
                }
                ,
            }
            ;

        var expected =
"""
[2	]{id}:
  1
  2
""";

        // Act & Assert
        var options = new LegacyToonEncodeOptions
        {
            Delimiter = ToonDelimiter.TAB,
        };

        var result = ToonEncoder.Encode(input, options);

        Assert.Equal(expected, result);
    }

    [Fact]
    [Trait("Description", "encodes root-level array of objects with pipe delimiter")]
    public void EncodesRootLevelArrayOfObjectsWithPipeDelimiter()
    {
        // Arrange
        var input =
            new object[] {            
                new
                {
                    @id = 1,
                }
                ,
                new
                {
                    @id = 2,
                }
                ,
            }
            ;

        var expected =
"""
[2|]{id}:
  1
  2
""";

        // Act & Assert
        var options = new LegacyToonEncodeOptions
        {
            Delimiter = ToonDelimiter.PIPE,
        };

        var result = ToonEncoder.Encode(input, options);

        Assert.Equal(expected, result);
    }

    [Fact]
    [Trait("Description", "quotes strings containing tab delimiter")]
    public void QuotesStringsContainingTabDelimiter()
    {
        // Arrange
        var input =
            new
            {
                @items =new object[] {                
                    @"a",
                    @"b	c",
                    @"d",
                }
,
            }
            ;

        var expected =
"""
items[3	]: a	"b\tc"	d
""";

        // Act & Assert
        var options = new LegacyToonEncodeOptions
        {
            Delimiter = ToonDelimiter.TAB,
        };

        var result = ToonEncoder.Encode(input, options);

        Assert.Equal(expected, result);
    }

    [Fact]
    [Trait("Description", "quotes strings containing pipe delimiter")]
    public void QuotesStringsContainingPipeDelimiter()
    {
        // Arrange
        var input =
            new
            {
                @items =new object[] {                
                    @"a",
                    @"b|c",
                    @"d",
                }
,
            }
            ;

        var expected =
"""
items[3|]: a|"b|c"|d
""";

        // Act & Assert
        var options = new LegacyToonEncodeOptions
        {
            Delimiter = ToonDelimiter.PIPE,
        };

        var result = ToonEncoder.Encode(input, options);

        Assert.Equal(expected, result);
    }

    [Fact]
    [Trait("Description", "does not quote commas with tab delimiter")]
    public void DoesNotQuoteCommasWithTabDelimiter()
    {
        // Arrange
        var input =
            new
            {
                @items =new object[] {                
                    @"a,b",
                    @"c,d",
                }
,
            }
            ;

        var expected =
"""
items[2	]: a,b	c,d
""";

        // Act & Assert
        var options = new LegacyToonEncodeOptions
        {
            Delimiter = ToonDelimiter.TAB,
        };

        var result = ToonEncoder.Encode(input, options);

        Assert.Equal(expected, result);
    }

    [Fact]
    [Trait("Description", "does not quote commas with pipe delimiter")]
    public void DoesNotQuoteCommasWithPipeDelimiter()
    {
        // Arrange
        var input =
            new
            {
                @items =new object[] {                
                    @"a,b",
                    @"c,d",
                }
,
            }
            ;

        var expected =
"""
items[2|]: a,b|c,d
""";

        // Act & Assert
        var options = new LegacyToonEncodeOptions
        {
            Delimiter = ToonDelimiter.PIPE,
        };

        var result = ToonEncoder.Encode(input, options);

        Assert.Equal(expected, result);
    }

    [Fact]
    [Trait("Description", "quotes tabular values containing comma delimiter")]
    public void QuotesTabularValuesContainingCommaDelimiter()
    {
        // Arrange
        var input =
            new
            {
                @items =new object[] {                
                    new
                    {
                        @id = 1,
                        @note = @"a,b",
                    }
                    ,
                    new
                    {
                        @id = 2,
                        @note = @"c,d",
                    }
                    ,
                }
,
            }
            ;

        var expected =
"""
items[2]{id,note}:
  1,"a,b"
  2,"c,d"
""";

        // Act & Assert
        var options = new LegacyToonEncodeOptions
        {
            Delimiter = ToonDelimiter.COMMA,
        };

        var result = ToonEncoder.Encode(input, options);

        Assert.Equal(expected, result);
    }

    [Fact]
    [Trait("Description", "does not quote commas in tabular values with tab delimiter")]
    public void DoesNotQuoteCommasInTabularValuesWithTabDelimiter()
    {
        // Arrange
        var input =
            new
            {
                @items =new object[] {                
                    new
                    {
                        @id = 1,
                        @note = @"a,b",
                    }
                    ,
                    new
                    {
                        @id = 2,
                        @note = @"c,d",
                    }
                    ,
                }
,
            }
            ;

        var expected =
"""
items[2	]{id	note}:
  1	a,b
  2	c,d
""";

        // Act & Assert
        var options = new LegacyToonEncodeOptions
        {
            Delimiter = ToonDelimiter.TAB,
        };

        var result = ToonEncoder.Encode(input, options);

        Assert.Equal(expected, result);
    }

    [Fact]
    [Trait("Description", "does not quote commas in object values with pipe delimiter")]
    public void DoesNotQuoteCommasInObjectValuesWithPipeDelimiter()
    {
        // Arrange
        var input =
            new
            {
                @note = @"a,b",
            }
            ;

        var expected =
"""
note: a,b
""";

        // Act & Assert
        var options = new LegacyToonEncodeOptions
        {
            Delimiter = ToonDelimiter.PIPE,
        };

        var result = ToonEncoder.Encode(input, options);

        Assert.Equal(expected, result);
    }

    [Fact]
    [Trait("Description", "does not quote commas in object values with tab delimiter")]
    public void DoesNotQuoteCommasInObjectValuesWithTabDelimiter()
    {
        // Arrange
        var input =
            new
            {
                @note = @"a,b",
            }
            ;

        var expected =
"""
note: a,b
""";

        // Act & Assert
        var options = new LegacyToonEncodeOptions
        {
            Delimiter = ToonDelimiter.TAB,
        };

        var result = ToonEncoder.Encode(input, options);

        Assert.Equal(expected, result);
    }

    [Fact]
    [Trait("Description", "quotes nested array values containing pipe delimiter")]
    public void QuotesNestedArrayValuesContainingPipeDelimiter()
    {
        // Arrange
        var input =
            new
            {
                @pairs =new object[] {                
                    new object[] {                    
                        @"a",
                        @"b|c",
                    }
                    ,
                }
,
            }
            ;

        var expected =
"""
pairs[1|]:
  - [2|]: a|"b|c"
""";

        // Act & Assert
        var options = new LegacyToonEncodeOptions
        {
            Delimiter = ToonDelimiter.PIPE,
        };

        var result = ToonEncoder.Encode(input, options);

        Assert.Equal(expected, result);
    }

    [Fact]
    [Trait("Description", "quotes nested array values containing tab delimiter")]
    public void QuotesNestedArrayValuesContainingTabDelimiter()
    {
        // Arrange
        var input =
            new
            {
                @pairs =new object[] {                
                    new object[] {                    
                        @"a",
                        @"b	c",
                    }
                    ,
                }
,
            }
            ;

        var expected =
"""
pairs[1	]:
  - [2	]: a	"b\tc"
""";

        // Act & Assert
        var options = new LegacyToonEncodeOptions
        {
            Delimiter = ToonDelimiter.TAB,
        };

        var result = ToonEncoder.Encode(input, options);

        Assert.Equal(expected, result);
    }

    [Fact]
    [Trait("Description", "preserves ambiguity quoting regardless of delimiter")]
    public void PreservesAmbiguityQuotingRegardlessOfDelimiter()
    {
        // Arrange
        var input =
            new
            {
                @items =new object[] {                
                    @"true",
                    @"42",
                    @"-3.14",
                }
,
            }
            ;

        var expected =
"""
items[3|]: "true"|"42"|"-3.14"
""";

        // Act & Assert
        var options = new LegacyToonEncodeOptions
        {
            Delimiter = ToonDelimiter.PIPE,
        };

        var result = ToonEncoder.Encode(input, options);

        Assert.Equal(expected, result);
    }

}
