// <auto-generated>
//     This code was generated by DevOp.Toon.SpecGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>


using System;
using System.Collections.Generic;
using System.Text.Json;
using DevOp.Toon;
using Xunit;


namespace DevOp.Toon.Tests.Encode;


[Trait("Category", "encode")]
public class Objects
{
    [Fact]
    [Trait("Description", "preserves key order in objects")]
    public void PreservesKeyOrderInObjects()
    {
        // Arrange
        var input =
            new
            {
                @id = 123,
                @name = @"Ada",
                @active = true,
            }
            ;

        var expected =
"""
id: 123
name: Ada
active: true
""";

        // Act & Assert
        var result = ToonEncoder.Encode(input, new LegacyDefaultToonEncodeOptions());

        Assert.Equal(expected, result);
    }

    [Fact]
    [Trait("Description", "encodes null values in objects")]
    public void EncodesNullValuesInObjects()
    {
        // Arrange
        var input =
            new
            {
                @id = 123,
                @value = (string)null,            }
            ;

        var expected =
"""
id: 123
value: null
""";

        // Act & Assert
        var result = ToonEncoder.Encode(input, new LegacyDefaultToonEncodeOptions());

        Assert.Equal(expected, result);
    }

    [Fact]
    [Trait("Description", "encodes empty objects as empty string")]
    public void EncodesEmptyObjectsAsEmptyString()
    {
        // Arrange
        var input =
            new
            {
            }
            ;

        var expected =
"""

""";

        // Act & Assert
        var result = ToonEncoder.Encode(input, new LegacyDefaultToonEncodeOptions());

        Assert.Equal(expected, result);
    }

    [Fact]
    [Trait("Description", "quotes string value with colon")]
    public void QuotesStringValueWithColon()
    {
        // Arrange
        var input =
            new
            {
                @note = @"a:b",
            }
            ;

        var expected =
"""
note: "a:b"
""";

        // Act & Assert
        var result = ToonEncoder.Encode(input, new LegacyDefaultToonEncodeOptions());

        Assert.Equal(expected, result);
    }

    [Fact]
    [Trait("Description", "quotes string value with comma")]
    public void QuotesStringValueWithComma()
    {
        // Arrange
        var input =
            new
            {
                @note = @"a,b",
            }
            ;

        var expected =
"""
note: "a,b"
""";

        // Act & Assert
        var result = ToonEncoder.Encode(input, new LegacyDefaultToonEncodeOptions());

        Assert.Equal(expected, result);
    }

    [Fact]
    [Trait("Description", "quotes string value with newline")]
    public void QuotesStringValueWithNewline()
    {
        // Arrange
        var input =
            new
            {
                @text = @"line1
line2",
            }
            ;

        var expected =
"""
text: "line1\nline2"
""";

        // Act & Assert
        var result = ToonEncoder.Encode(input, new LegacyDefaultToonEncodeOptions());

        Assert.Equal(expected, result);
    }

    [Fact]
    [Trait("Description", "quotes string value with embedded quotes")]
    public void QuotesStringValueWithEmbeddedQuotes()
    {
        // Arrange
        var input =
            new
            {
                @text = @"say ""hello""",
            }
            ;

        var expected =
"""
text: "say \"hello\""
""";

        // Act & Assert
        var result = ToonEncoder.Encode(input, new LegacyDefaultToonEncodeOptions());

        Assert.Equal(expected, result);
    }

    [Fact]
    [Trait("Description", "quotes string value with leading space")]
    public void QuotesStringValueWithLeadingSpace()
    {
        // Arrange
        var input =
            new
            {
                @text = @" padded ",
            }
            ;

        var expected =
"""
text: " padded "
""";

        // Act & Assert
        var result = ToonEncoder.Encode(input, new LegacyDefaultToonEncodeOptions());

        Assert.Equal(expected, result);
    }

    [Fact]
    [Trait("Description", "quotes string value with only spaces")]
    public void QuotesStringValueWithOnlySpaces()
    {
        // Arrange
        var input =
            new
            {
                @text = @"  ",
            }
            ;

        var expected =
"""
text: "  "
""";

        // Act & Assert
        var result = ToonEncoder.Encode(input, new LegacyDefaultToonEncodeOptions());

        Assert.Equal(expected, result);
    }

    [Fact]
    [Trait("Description", "quotes string value that looks like true")]
    public void QuotesStringValueThatLooksLikeTrue()
    {
        // Arrange
        var input =
            new
            {
                @v = @"true",
            }
            ;

        var expected =
"""
v: "true"
""";

        // Act & Assert
        var result = ToonEncoder.Encode(input, new LegacyDefaultToonEncodeOptions());

        Assert.Equal(expected, result);
    }

    [Fact]
    [Trait("Description", "quotes string value that looks like number")]
    public void QuotesStringValueThatLooksLikeNumber()
    {
        // Arrange
        var input =
            new
            {
                @v = @"42",
            }
            ;

        var expected =
"""
v: "42"
""";

        // Act & Assert
        var result = ToonEncoder.Encode(input, new LegacyDefaultToonEncodeOptions());

        Assert.Equal(expected, result);
    }

    [Fact]
    [Trait("Description", "quotes string value that looks like negative decimal")]
    public void QuotesStringValueThatLooksLikeNegativeDecimal()
    {
        // Arrange
        var input =
            new
            {
                @v = @"-7.5",
            }
            ;

        var expected =
"""
v: "-7.5"
""";

        // Act & Assert
        var result = ToonEncoder.Encode(input, new LegacyDefaultToonEncodeOptions());

        Assert.Equal(expected, result);
    }

    [Fact]
    [Trait("Description", "encodes deeply nested objects")]
    public void EncodesDeeplyNestedObjects()
    {
        // Arrange
        var input =
            new
            {
                @a =
                new
                {
                    @b =
                    new
                    {
                        @c = @"deep",
                    }
,
                }
,
            }
            ;

        var expected =
"""
a:
  b:
    c: deep
""";

        // Act & Assert
        var result = ToonEncoder.Encode(input, new LegacyToonEncodeOptions());

        Assert.Equal(expected, result);
    }

    [Fact]
    [Trait("Description", "encodes empty nested object")]
    public void EncodesEmptyNestedObject()
    {
        // Arrange
        var input =
            new
            {
                @user =
                new
                {
                }
,
            }
            ;

        var expected =
"""
user:
""";

        // Act & Assert
        var result = ToonEncoder.Encode(input, new LegacyDefaultToonEncodeOptions());

        Assert.Equal(expected, result);
    }

}
