// <auto-generated>
//     This code was generated by DevOp.Toon.SpecGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>


using System;
using System.Collections.Generic;
using System.Text.Json;
using DevOp.Toon;
using Xunit;


namespace DevOp.Toon.Tests.Encode;


[Trait("Category", "encode")]
public class Primitives
{
    [Fact]
    [Trait("Description", "encodes safe strings without quotes")]
    public void EncodesSafeStringsWithoutQuotes()
    {
        // Arrange
        var input =
            @"hello"            ;

        var expected =
"""
hello
""";

        // Act & Assert
        var result = ToonEncoder.Encode(input);

        Assert.Equal(expected, result);
    }

    [Fact]
    [Trait("Description", "encodes safe string with underscore and numbers")]
    public void EncodesSafeStringWithUnderscoreAndNumbers()
    {
        // Arrange
        var input =
            @"Ada_99"            ;

        var expected =
"""
Ada_99
""";

        // Act & Assert
        var result = ToonEncoder.Encode(input);

        Assert.Equal(expected, result);
    }

    [Fact]
    [Trait("Description", "quotes empty string")]
    public void QuotesEmptyString()
    {
        // Arrange
        var input =
            @""            ;

        var expected =
"""
""
""";

        // Act & Assert
        var result = ToonEncoder.Encode(input);

        Assert.Equal(expected, result);
    }

    [Fact]
    [Trait("Description", "quotes string that looks like true")]
    public void QuotesStringThatLooksLikeTrue()
    {
        // Arrange
        var input =
            @"true"            ;

        var expected =
"""
"true"
""";

        // Act & Assert
        var result = ToonEncoder.Encode(input);

        Assert.Equal(expected, result);
    }

    [Fact]
    [Trait("Description", "quotes string that looks like false")]
    public void QuotesStringThatLooksLikeFalse()
    {
        // Arrange
        var input =
            @"false"            ;

        var expected =
"""
"false"
""";

        // Act & Assert
        var result = ToonEncoder.Encode(input);

        Assert.Equal(expected, result);
    }

    [Fact]
    [Trait("Description", "quotes string that looks like null")]
    public void QuotesStringThatLooksLikeNull()
    {
        // Arrange
        var input =
            @"null"            ;

        var expected =
"""
"null"
""";

        // Act & Assert
        var result = ToonEncoder.Encode(input);

        Assert.Equal(expected, result);
    }

    [Fact]
    [Trait("Description", "quotes string that looks like integer")]
    public void QuotesStringThatLooksLikeInteger()
    {
        // Arrange
        var input =
            @"42"            ;

        var expected =
"""
"42"
""";

        // Act & Assert
        var result = ToonEncoder.Encode(input);

        Assert.Equal(expected, result);
    }

    [Fact]
    [Trait("Description", "quotes string that looks like negative decimal")]
    public void QuotesStringThatLooksLikeNegativeDecimal()
    {
        // Arrange
        var input =
            @"-3.14"            ;

        var expected =
"""
"-3.14"
""";

        // Act & Assert
        var result = ToonEncoder.Encode(input);

        Assert.Equal(expected, result);
    }

    [Fact]
    [Trait("Description", "quotes string that looks like scientific notation")]
    public void QuotesStringThatLooksLikeScientificNotation()
    {
        // Arrange
        var input =
            @"1e-6"            ;

        var expected =
"""
"1e-6"
""";

        // Act & Assert
        var result = ToonEncoder.Encode(input);

        Assert.Equal(expected, result);
    }

    [Fact]
    [Trait("Description", "quotes string with leading zero")]
    public void QuotesStringWithLeadingZero()
    {
        // Arrange
        var input =
            @"05"            ;

        var expected =
"""
"05"
""";

        // Act & Assert
        var result = ToonEncoder.Encode(input);

        Assert.Equal(expected, result);
    }

    [Fact]
    [Trait("Description", "escapes newline in string")]
    public void EscapesNewlineInString()
    {
        // Arrange
        var input =
            @"line1
line2"            ;

        var expected =
"""
"line1\nline2"
""";

        // Act & Assert
        var result = ToonEncoder.Encode(input);

        Assert.Equal(expected, result);
    }

    [Fact]
    [Trait("Description", "escapes tab in string")]
    public void EscapesTabInString()
    {
        // Arrange
        var input =
            @"tab	here"            ;

        var expected =
"""
"tab\there"
""";

        // Act & Assert
        var result = ToonEncoder.Encode(input);

        Assert.Equal(expected, result);
    }

    [Fact]
    [Trait("Description", "escapes carriage return in string")]
    public void EscapesCarriageReturnInString()
    {
        // Arrange
        var input =
            @"returncarriage"            ;

        var expected =
"""
"return\rcarriage"
""";

        // Act & Assert
        var result = ToonEncoder.Encode(input);

        Assert.Equal(expected, result);
    }

    [Fact]
    [Trait("Description", "escapes backslash in string")]
    public void EscapesBackslashInString()
    {
        // Arrange
        var input =
            @"C:\Users\path"            ;

        var expected =
"""
"C:\\Users\\path"
""";

        // Act & Assert
        var result = ToonEncoder.Encode(input);

        Assert.Equal(expected, result);
    }

    [Fact]
    [Trait("Description", "quotes string with array-like syntax")]
    public void QuotesStringWithArrayLikeSyntax()
    {
        // Arrange
        var input =
            @"[3]: x,y"            ;

        var expected =
"""
"[3]: x,y"
""";

        // Act & Assert
        var result = ToonEncoder.Encode(input);

        Assert.Equal(expected, result);
    }

    [Fact]
    [Trait("Description", "quotes string starting with hyphen-space")]
    public void QuotesStringStartingWithHyphenSpace()
    {
        // Arrange
        var input =
            @"- item"            ;

        var expected =
"""
"- item"
""";

        // Act & Assert
        var result = ToonEncoder.Encode(input);

        Assert.Equal(expected, result);
    }

    [Fact]
    [Trait("Description", "quotes single hyphen as object value")]
    public void QuotesSingleHyphenAsObjectValue()
    {
        // Arrange
        var input =
            new
            {
                @marker = @"-",
            }
            ;

        var expected =
"""
marker: "-"
""";

        // Act & Assert
        var result = ToonEncoder.Encode(input);

        Assert.Equal(expected, result);
    }

    [Fact]
    [Trait("Description", "quotes string starting with hyphen as object value")]
    public void QuotesStringStartingWithHyphenAsObjectValue()
    {
        // Arrange
        var input =
            new
            {
                @note = @"- item",
            }
            ;

        var expected =
"""
note: "- item"
""";

        // Act & Assert
        var result = ToonEncoder.Encode(input);

        Assert.Equal(expected, result);
    }

    [Fact]
    [Trait("Description", "quotes single hyphen in array")]
    public void QuotesSingleHyphenInArray()
    {
        // Arrange
        var input =
            new
            {
                @items =new object[] {                
                    @"-",
                }
,
            }
            ;

        var expected =
"""
items[1]: "-"
""";

        // Act & Assert
        var result = ToonEncoder.Encode(input);

        Assert.Equal(expected, result);
    }

    [Fact]
    [Trait("Description", "quotes leading-hyphen string in array")]
    public void QuotesLeadingHyphenStringInArray()
    {
        // Arrange
        var input =
            new
            {
                @tags =new object[] {                
                    @"a",
                    @"- item",
                    @"b",
                }
,
            }
            ;

        var expected =
"""
tags[3]: a,"- item",b
""";

        // Act & Assert
        var result = ToonEncoder.Encode(input);

        Assert.Equal(expected, result);
    }

    [Fact]
    [Trait("Description", "quotes string with bracket notation")]
    public void QuotesStringWithBracketNotation()
    {
        // Arrange
        var input =
            @"[test]"            ;

        var expected =
"""
"[test]"
""";

        // Act & Assert
        var result = ToonEncoder.Encode(input);

        Assert.Equal(expected, result);
    }

    [Fact]
    [Trait("Description", "quotes string with brace notation")]
    public void QuotesStringWithBraceNotation()
    {
        // Arrange
        var input =
            @"{key}"            ;

        var expected =
"""
"{key}"
""";

        // Act & Assert
        var result = ToonEncoder.Encode(input);

        Assert.Equal(expected, result);
    }

    [Fact]
    [Trait("Description", "encodes Unicode string without quotes")]
    public void EncodesUnicodeStringWithoutQuotes()
    {
        // Arrange
        var input =
            @"cafÃ©"            ;

        var expected =
"""
cafÃ©
""";

        // Act & Assert
        var result = ToonEncoder.Encode(input);

        Assert.Equal(expected, result);
    }

    [Fact]
    [Trait("Description", "encodes Chinese characters without quotes")]
    public void EncodesChineseCharactersWithoutQuotes()
    {
        // Arrange
        var input =
            @"ä½ å¥½"            ;

        var expected =
"""
ä½ å¥½
""";

        // Act & Assert
        var result = ToonEncoder.Encode(input);

        Assert.Equal(expected, result);
    }

    [Fact]
    [Trait("Description", "encodes emoji without quotes")]
    public void EncodesEmojiWithoutQuotes()
    {
        // Arrange
        var input =
            @"ðŸš€"            ;

        var expected =
"""
ðŸš€
""";

        // Act & Assert
        var result = ToonEncoder.Encode(input);

        Assert.Equal(expected, result);
    }

    [Fact]
    [Trait("Description", "encodes string with emoji and spaces")]
    public void EncodesStringWithEmojiAndSpaces()
    {
        // Arrange
        var input =
            @"hello ðŸ‘‹ world"            ;

        var expected =
"""
hello ðŸ‘‹ world
""";

        // Act & Assert
        var result = ToonEncoder.Encode(input);

        Assert.Equal(expected, result);
    }

    [Fact]
    [Trait("Description", "encodes positive integer")]
    public void EncodesPositiveInteger()
    {
        // Arrange
        var input =
            42            ;

        var expected =
"""
42
""";

        // Act & Assert
        var result = ToonEncoder.Encode(input);

        Assert.Equal(expected, result);
    }

    [Fact]
    [Trait("Description", "encodes decimal number")]
    public void EncodesDecimalNumber()
    {
        // Arrange
        var input =
            3.14            ;

        var expected =
"""
3.14
""";

        // Act & Assert
        var result = ToonEncoder.Encode(input);

        Assert.Equal(expected, result);
    }

    [Fact]
    [Trait("Description", "encodes negative integer")]
    public void EncodesNegativeInteger()
    {
        // Arrange
        var input =
            -7            ;

        var expected =
"""
-7
""";

        // Act & Assert
        var result = ToonEncoder.Encode(input);

        Assert.Equal(expected, result);
    }

    [Fact]
    [Trait("Description", "encodes zero")]
    public void EncodesZero()
    {
        // Arrange
        var input =
            0            ;

        var expected =
"""
0
""";

        // Act & Assert
        var result = ToonEncoder.Encode(input);

        Assert.Equal(expected, result);
    }

    [Fact]
    [Trait("Description", "encodes negative zero as zero")]
    public void EncodesNegativeZeroAsZero()
    {
        // Arrange
        var input =
            -0            ;

        var expected =
"""
0
""";

        // Act & Assert
        var result = ToonEncoder.Encode(input);

        Assert.Equal(expected, result);
    }

    [Fact]
    [Trait("Description", "encodes scientific notation as decimal")]
    public void EncodesScientificNotationAsDecimal()
    {
        // Arrange
        var input =
            1000000            ;

        var expected =
"""
1000000
""";

        // Act & Assert
        var result = ToonEncoder.Encode(input);

        Assert.Equal(expected, result);
    }

    [Fact]
    [Trait("Description", "encodes small decimal from scientific notation")]
    public void EncodesSmallDecimalFromScientificNotation()
    {
        // Arrange
        var input =
            0.000001            ;

        var expected =
"""
0.000001
""";

        // Act & Assert
        var result = ToonEncoder.Encode(input);

        Assert.Equal(expected, result);
    }

    [Fact]
    [Trait("Description", "encodes MAX_SAFE_INTEGER")]
    public void EncodesMaxSafeInteger()
    {
        // Arrange
        var input =
            9007199254740991            ;

        var expected =
"""
9007199254740991
""";

        // Act & Assert
        var result = ToonEncoder.Encode(input);

        Assert.Equal(expected, result);
    }

    [Fact]
    [Trait("Description", "encodes repeating decimal with full precision")]
    public void EncodesRepeatingDecimalWithFullPrecision()
    {
        // Arrange
        var input =
            0.3333333333333333            ;

        var expected =
"""
0.3333333333333333
""";

        // Act & Assert
        var result = ToonEncoder.Encode(input);

        Assert.Equal(expected, result);
    }

    [Fact]
    [Trait("Description", "encodes true")]
    public void EncodesTrue()
    {
        // Arrange
        var input =
            true            ;

        var expected =
"""
true
""";

        // Act & Assert
        var result = ToonEncoder.Encode(input);

        Assert.Equal(expected, result);
    }

    [Fact]
    [Trait("Description", "encodes false")]
    public void EncodesFalse()
    {
        // Arrange
        var input =
            false            ;

        var expected =
"""
false
""";

        // Act & Assert
        var result = ToonEncoder.Encode(input);

        Assert.Equal(expected, result);
    }

    [Fact]
    [Trait("Description", "encodes null")]
    public void EncodesNull()
    {
        // Arrange
        var input =
            (string)null            ;

        var expected =
"""
null
""";

        // Act & Assert
        var result = ToonEncoder.Encode(input);

        Assert.Equal(expected, result);
    }

}
