// <auto-generated>
//     This code was generated by DevOp.Toon.SpecGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>


using System;
using System.Collections.Generic;
using System.Text.Json;
using DevOp.Toon;
using Xunit;


namespace DevOp.Toon.Tests.Encode;


[Trait("Category", "encode")]
public class Whitespace
{
    [Fact]
    [Trait("Description", "produces no trailing newline at end of output")]
    public void ProducesNoTrailingNewlineAtEndOfOutput()
    {
        // Arrange
        var input =
            new
            {
                @id = 123,
            }
            ;

        var expected =
"""
id: 123
""";

        // Act & Assert
        var result = ToonEncoder.Encode(input, new LegacyDefaultToonEncodeOptions());

        Assert.Equal(expected, result);
    }

    [Fact]
    [Trait("Description", "maintains proper indentation for nested structures")]
    public void MaintainsProperIndentationForNestedStructures()
    {
        // Arrange
        var input =
            new
            {
                @user =
                new
                {
                    @id = 123,
                    @name = @"Ada",
                }
,
                @items =new object[] {                
                    @"a",
                    @"b",
                }
,
            }
            ;

        var expected =
"""
user:
  id: 123
  name: Ada
items[2]: a,b
""";

        // Act & Assert
        var result = ToonEncoder.Encode(input, new LegacyDefaultToonEncodeOptions());

        Assert.Equal(expected, result);
    }

    [Fact]
    [Trait("Description", "respects custom indent size option")]
    public void RespectsCustomIndentSizeOption()
    {
        // Arrange
        var input =
            new
            {
                @user =
                new
                {
                    @name = @"Ada",
                    @role = @"admin",
                }
,
            }
            ;

        var expected =
"""
user:
    name: Ada
    role: admin
""";

        // Act & Assert
        var options = new LegacyToonEncodeOptions
        {
            Indent = 4,
        };

        var result = ToonEncoder.Encode(input, options);

        Assert.Equal(expected, result);
    }

}
